INSERT INTO public.mock_tests (id, title, description, exam_type, module, difficulty, duration_minutes, is_premium, created_at, updated_at)
VALUES
('a2288c0d-ed58-4f18-b118-2a9f019e3af9', 'TEF Compréhension Écrite - B1-C1', 'Examen de pratique niveau B1-C1 pour TEF avec documents authentiques.', 'tef', 'reading', 'advanced', 60, True, '2026-07-18T04:12:22.151868', '2026-07-18T04:12:22.151880'),
('54f063d3-a352-4e1b-b8cd-95fe076c9153', 'TEF Compréhension Orale - B1-C1', 'Pratique intensive de la compréhension orale TEF niveau B1-C1.', 'tef', 'listening', 'advanced', 40, True, '2026-07-18T04:12:22.152101', '2026-07-18T04:12:22.152102'),
('9021506f-d97d-4181-98c5-275916405ee2', 'TCF Compréhension Écrite - B1-C1', 'Examen de pratique niveau B1-C1 pour TCF avec documents authentiques.', 'tcf', 'reading', 'advanced', 60, True, '2026-07-18T04:12:22.152357', '2026-07-18T04:12:22.152358'),
('85f94a53-c5ee-490b-8f83-901082764b10', 'TCF Compréhension Orale - B1-C1', 'Pratique intensive de la compréhension orale TCF niveau B1-C1.', 'tcf', 'listening', 'advanced', 40, True, '2026-07-18T04:12:22.152475', '2026-07-18T04:12:22.152477'),
('c07e56de-6700-4461-8ce4-e7f8005fe8f1', 'TEF Expression Écrite - B1-C1', 'Sections A et B de l''épreuve d''expression écrite TEF niveau avancé.', 'tef', 'writing', 'advanced', 60, True, '2026-07-18T04:12:22.152570', '2026-07-18T04:12:22.152572'),
('c6ee9da4-4898-43c1-a660-4e33a8c1311c', 'TEF Expression Orale - B1-C1', 'Épreuves de conversation avancées pour TEF.', 'tef', 'speaking', 'advanced', 15, True, '2026-07-18T04:12:22.152602', '2026-07-18T04:12:22.152604'),
('dd264253-d558-466e-bf2b-79be230e08a2', 'TCF Expression Écrite - B1-C1', 'Sections A et B de l''épreuve d''expression écrite TCF niveau avancé.', 'tcf', 'writing', 'advanced', 60, True, '2026-07-18T04:12:22.152625', '2026-07-18T04:12:22.152627'),
('b099f02b-bf61-48ff-b4f9-0c730d3a8d51', 'TCF Expression Orale - B1-C1', 'Épreuves de conversation avancées pour TCF.', 'tcf', 'speaking', 'advanced', 15, True, '2026-07-18T04:12:22.152653', '2026-07-18T04:12:22.152654');

INSERT INTO public.test_questions (id, test_id, question_text, audio_url, image_url, options, correct_answer, explanation, points, order_index, created_at)
VALUES
('dd5d4c49-d406-4774-abe5-be6473d5a1a1', 'a2288c0d-ed58-4f18-b118-2a9f019e3af9', 'Le gouvernement canadien a récemment dévoilé son plan d''action national pour la transition écologique, un document de 150 pages qui fixe des objectifs ambitieux pour réduire les émissions de gaz à effet de serre de 45% d''ici 2030 par rapport aux niveaux de 2005. Ce plan, qui s''inscrit dans le cadre de l''Accord de Paris, prévoit des investissements majeurs dans les énergies renouvelables, l''électrification des transports et l''efficacité énergétique des bâtiments. Parmi les mesures phares, on trouve l''installation de bornes de recharge pour véhicules électriques sur l''ensemble du territoire, des subventions pour la rénovation énergétique des logements anciens, et un soutien accru à la recherche et développement dans le secteur des technologies vertes. Le gouvernement estime que ces mesures pourraient créer jusqu''à 200 000 emplois dans les prochaines années. Cependant, ce plan fait face à des critiques. Certains groupes environnementaux estiment que les objectifs ne sont pas assez ambitieux, tandis que des représentants du secteur pétrolier s''inquiètent des conséquences économiques pour les régions dépendantes des hydrocarbures.

Question : Quel est l''objectif principal du plan d''action national pour la transition écologique ?', NULL, NULL, '["R\u00e9duire les \u00e9missions de GES de 45% d''ici 2030", "\u00c9liminer compl\u00e8tement les hydrocarbures d''ici 2030", "Cr\u00e9er 500 000 emplois verts", "Atteindre la neutralit\u00e9 carbone en 2025"]', 'Réduire les émissions de GES de 45% d''ici 2030', '''Réduire les émissions de GES de 45% d''ici 2030'' est la réponse correcte d''après le texte fourni.', 1, 0, '2026-07-18T04:12:22.151912'),
('a137346b-c2f0-4f10-ab88-91d6c18e7986', 'a2288c0d-ed58-4f18-b118-2a9f019e3af9', 'Le gouvernement canadien a récemment dévoilé son plan d''action national pour la transition écologique, un document de 150 pages qui fixe des objectifs ambitieux pour réduire les émissions de gaz à effet de serre de 45% d''ici 2030 par rapport aux niveaux de 2005. Ce plan, qui s''inscrit dans le cadre de l''Accord de Paris, prévoit des investissements majeurs dans les énergies renouvelables, l''électrification des transports et l''efficacité énergétique des bâtiments. Parmi les mesures phares, on trouve l''installation de bornes de recharge pour véhicules électriques sur l''ensemble du territoire, des subventions pour la rénovation énergétique des logements anciens, et un soutien accru à la recherche et développement dans le secteur des technologies vertes. Le gouvernement estime que ces mesures pourraient créer jusqu''à 200 000 emplois dans les prochaines années. Cependant, ce plan fait face à des critiques. Certains groupes environnementaux estiment que les objectifs ne sont pas assez ambitieux, tandis que des représentants du secteur pétrolier s''inquiètent des conséquences économiques pour les régions dépendantes des hydrocarbures.

Question : Quelles sont les mesures phares mentionnées dans le plan ?', NULL, NULL, '["L''installation de bornes de recharge, des subventions pour la r\u00e9novation, et le soutien \u00e0 la R&D", "La construction de nouvelles centrales nucl\u00e9aires et l''exportation de p\u00e9trole", "L''interdiction totale des v\u00e9hicules thermiques et la taxation du carbone", "La fermeture des industries polluantes et la d\u00e9localisation"]', 'L''installation de bornes de recharge, des subventions pour la rénovation, et le soutien à la R&D', '''L''installation de bornes de recharge, des subventions pour la rénovation, et le soutien à la R&D'' est la réponse correcte d''après le texte fourni.', 1, 1, '2026-07-18T04:12:22.151962'),
('454fd9d0-b310-4851-bf3f-92db140dc9b1', 'a2288c0d-ed58-4f18-b118-2a9f019e3af9', 'Le gouvernement canadien a récemment dévoilé son plan d''action national pour la transition écologique, un document de 150 pages qui fixe des objectifs ambitieux pour réduire les émissions de gaz à effet de serre de 45% d''ici 2030 par rapport aux niveaux de 2005. Ce plan, qui s''inscrit dans le cadre de l''Accord de Paris, prévoit des investissements majeurs dans les énergies renouvelables, l''électrification des transports et l''efficacité énergétique des bâtiments. Parmi les mesures phares, on trouve l''installation de bornes de recharge pour véhicules électriques sur l''ensemble du territoire, des subventions pour la rénovation énergétique des logements anciens, et un soutien accru à la recherche et développement dans le secteur des technologies vertes. Le gouvernement estime que ces mesures pourraient créer jusqu''à 200 000 emplois dans les prochaines années. Cependant, ce plan fait face à des critiques. Certains groupes environnementaux estiment que les objectifs ne sont pas assez ambitieux, tandis que des représentants du secteur pétrolier s''inquiètent des conséquences économiques pour les régions dépendantes des hydrocarbures.

Question : Combien d''emplois ces mesures pourraient-elles créer selon le gouvernement ?', NULL, NULL, '["50 000", "100 000", "200 000", "500 000"]', '200 000', '''200 000'' est la réponse correcte d''après le texte fourni.', 1, 2, '2026-07-18T04:12:22.151984'),
('89a44b2c-a729-42e6-9ddb-6efee9344121', 'a2288c0d-ed58-4f18-b118-2a9f019e3af9', 'Le gouvernement canadien a récemment dévoilé son plan d''action national pour la transition écologique, un document de 150 pages qui fixe des objectifs ambitieux pour réduire les émissions de gaz à effet de serre de 45% d''ici 2030 par rapport aux niveaux de 2005. Ce plan, qui s''inscrit dans le cadre de l''Accord de Paris, prévoit des investissements majeurs dans les énergies renouvelables, l''électrification des transports et l''efficacité énergétique des bâtiments. Parmi les mesures phares, on trouve l''installation de bornes de recharge pour véhicules électriques sur l''ensemble du territoire, des subventions pour la rénovation énergétique des logements anciens, et un soutien accru à la recherche et développement dans le secteur des technologies vertes. Le gouvernement estime que ces mesures pourraient créer jusqu''à 200 000 emplois dans les prochaines années. Cependant, ce plan fait face à des critiques. Certains groupes environnementaux estiment que les objectifs ne sont pas assez ambitieux, tandis que des représentants du secteur pétrolier s''inquiètent des conséquences économiques pour les régions dépendantes des hydrocarbures.

Question : Quelles sont les principales critiques adressées à ce plan ?', NULL, NULL, '["Il est trop ambitieux pour certains et pas assez pour d''autres", "Il est unanimement soutenu par tous les partis", "Il manque totalement de financement", "Il est jug\u00e9 inconstitutionnel"]', 'Il est trop ambitieux pour certains et pas assez pour d''autres', '''Il est trop ambitieux pour certains et pas assez pour d''autres'' est la réponse correcte d''après le texte fourni.', 1, 3, '2026-07-18T04:12:22.151999'),
('df42b81d-2a31-4dcb-b0a8-a2dbd54f5483', 'a2288c0d-ed58-4f18-b118-2a9f019e3af9', 'L''immigration joue un rôle fondamental dans le développement économique et démographique du Canada. Selon les données publiées par Statistique Canada, le pays a accueilli plus de 430 000 nouveaux résidents permanents en 2023, un chiffre record qui témoigne de la politique d''immigration ambitieuse du gouvernement fédéral. Les provinces qui ont connu la plus forte croissance démographique sont l''Ontario, la Colombie-Britannique et l''Alberta. Les nouveaux arrivants s''installent majoritairement dans les grands centres urbains comme Toronto, Vancouver et Montréal, attirés par les opportunités d''emploi et les services d''établissement. Le système de gestion des demandes d''immigration, basé sur le système de points Entrée express, a été conçu pour attirer des travailleurs qualifiés capables de contribuer rapidement à l''économie canadienne. Les critères de sélection prennent en compte l''âge, le niveau d''éducation, l''expérience professionnelle, les compétences linguistiques en français et en anglais, ainsi que la capacité d''adaptation. « L''immigration n''est pas seulement une nécessité économique, c''est aussi une source d''enrichissement culturel, » a souligné le ministre.

Question : Combien de nouveaux résidents permanents le Canada a-t-il accueilli en 2023 ?', NULL, NULL, '["Plus de 200 000", "Plus de 300 000", "Plus de 430 000", "Plus de 500 000"]', 'Plus de 430 000', '''Plus de 430 000'' est la réponse correcte d''après le texte fourni.', 1, 4, '2026-07-18T04:12:22.152012'),
('697abc81-3af4-4acc-8b98-85f12bdf58f6', 'a2288c0d-ed58-4f18-b118-2a9f019e3af9', 'L''immigration joue un rôle fondamental dans le développement économique et démographique du Canada. Selon les données publiées par Statistique Canada, le pays a accueilli plus de 430 000 nouveaux résidents permanents en 2023, un chiffre record qui témoigne de la politique d''immigration ambitieuse du gouvernement fédéral. Les provinces qui ont connu la plus forte croissance démographique sont l''Ontario, la Colombie-Britannique et l''Alberta. Les nouveaux arrivants s''installent majoritairement dans les grands centres urbains comme Toronto, Vancouver et Montréal, attirés par les opportunités d''emploi et les services d''établissement. Le système de gestion des demandes d''immigration, basé sur le système de points Entrée express, a été conçu pour attirer des travailleurs qualifiés capables de contribuer rapidement à l''économie canadienne. Les critères de sélection prennent en compte l''âge, le niveau d''éducation, l''expérience professionnelle, les compétences linguistiques en français et en anglais, ainsi que la capacité d''adaptation. « L''immigration n''est pas seulement une nécessité économique, c''est aussi une source d''enrichissement culturel, » a souligné le ministre.

Question : Quelles provinces ont connu la plus forte croissance démographique ?', NULL, NULL, '["Le Qu\u00e9bec et les provinces maritimes", "L''Ontario, la Colombie-Britannique et l''Alberta", "Le Manitoba, la Saskatchewan et les Territoires", "La Nouvelle-\u00c9cosse et Terre-Neuve"]', 'L''Ontario, la Colombie-Britannique et l''Alberta', '''L''Ontario, la Colombie-Britannique et l''Alberta'' est la réponse correcte d''après le texte fourni.', 1, 5, '2026-07-18T04:12:22.152024'),
('f124bc26-9ca1-4aff-8a97-315ddee8c12f', 'a2288c0d-ed58-4f18-b118-2a9f019e3af9', 'L''immigration joue un rôle fondamental dans le développement économique et démographique du Canada. Selon les données publiées par Statistique Canada, le pays a accueilli plus de 430 000 nouveaux résidents permanents en 2023, un chiffre record qui témoigne de la politique d''immigration ambitieuse du gouvernement fédéral. Les provinces qui ont connu la plus forte croissance démographique sont l''Ontario, la Colombie-Britannique et l''Alberta. Les nouveaux arrivants s''installent majoritairement dans les grands centres urbains comme Toronto, Vancouver et Montréal, attirés par les opportunités d''emploi et les services d''établissement. Le système de gestion des demandes d''immigration, basé sur le système de points Entrée express, a été conçu pour attirer des travailleurs qualifiés capables de contribuer rapidement à l''économie canadienne. Les critères de sélection prennent en compte l''âge, le niveau d''éducation, l''expérience professionnelle, les compétences linguistiques en français et en anglais, ainsi que la capacité d''adaptation. « L''immigration n''est pas seulement une nécessité économique, c''est aussi une source d''enrichissement culturel, » a souligné le ministre.

Question : Comment le système Entrée express sélectionne-t-il les candidats ?', NULL, NULL, '["Par tirage au sort", "Sur la base d''un syst\u00e8me de points incluant \u00e2ge, \u00e9ducation, exp\u00e9rience et langues", "Par ordre d''arriv\u00e9e des demandes", "Uniquement sur la base des comp\u00e9tences linguistiques"]', 'Sur la base d''un système de points incluant âge, éducation, expérience et langues', '''Sur la base d''un système de points incluant âge, éducation, expérience et langues'' est la réponse correcte d''après le texte fourni.', 1, 6, '2026-07-18T04:12:22.152042'),
('948022d5-034c-474a-afc1-272f400658d0', 'a2288c0d-ed58-4f18-b118-2a9f019e3af9', 'L''immigration joue un rôle fondamental dans le développement économique et démographique du Canada. Selon les données publiées par Statistique Canada, le pays a accueilli plus de 430 000 nouveaux résidents permanents en 2023, un chiffre record qui témoigne de la politique d''immigration ambitieuse du gouvernement fédéral. Les provinces qui ont connu la plus forte croissance démographique sont l''Ontario, la Colombie-Britannique et l''Alberta. Les nouveaux arrivants s''installent majoritairement dans les grands centres urbains comme Toronto, Vancouver et Montréal, attirés par les opportunités d''emploi et les services d''établissement. Le système de gestion des demandes d''immigration, basé sur le système de points Entrée express, a été conçu pour attirer des travailleurs qualifiés capables de contribuer rapidement à l''économie canadienne. Les critères de sélection prennent en compte l''âge, le niveau d''éducation, l''expérience professionnelle, les compétences linguistiques en français et en anglais, ainsi que la capacité d''adaptation. « L''immigration n''est pas seulement une nécessité économique, c''est aussi une source d''enrichissement culturel, » a souligné le ministre.

Question : Quels sont les défis persistants mentionnés ?', NULL, NULL, '["L''int\u00e9gration professionnelle, le logement abordable et la reconnaissance des dipl\u00f4mes", "Le climat, les infrastructures et les transports", "La s\u00e9curit\u00e9, l''\u00e9ducation et la sant\u00e9", "L''imp\u00f4t, la retraite et les assurances"]', 'L''intégration professionnelle, le logement abordable et la reconnaissance des diplômes', '''L''intégration professionnelle, le logement abordable et la reconnaissance des diplômes'' est la réponse correcte d''après le texte fourni.', 1, 7, '2026-07-18T04:12:22.152055'),
('727a1709-784e-40fe-87ec-97f33bccd03f', 'a2288c0d-ed58-4f18-b118-2a9f019e3af9', 'La Banque du Canada a annoncé une hausse de son taux directeur, le portant à 4,75%, une décision qui vise à contrer l''inflation persistante qui oscille autour de 3,5%. Cette augmentation, la quatrième en douze mois, aura des répercussions considérables sur les ménages canadiens, particulièrement ceux détenant un prêt hypothécaire à taux variable. Les économistes s''attendent à ce que le marché immobilier, déjà affecté par une baisse d''activité de 15% par rapport à l''année précédente, subisse un ralentissement supplémentaire. Par ailleurs, les entreprises qui dépendent du crédit pour financer leur expansion pourraient devoir revoir leurs plans d''investissement à la baisse. Cependant, la vigueur du marché du travail, avec un taux de chômage historiquement bas de 5,1%, pourrait atténuer l''impact de cette politique monétaire restrictive.

Question : Quel est le nouveau taux directeur annoncé par la Banque du Canada ?', NULL, NULL, '["3,5%", "4,75%", "5,1%", "6%"]', '4,75%', '''4,75%'' est la réponse correcte d''après le texte fourni.', 1, 8, '2026-07-18T04:12:22.152065'),
('ea681027-c61c-48e7-ab84-66f91ef53818', 'a2288c0d-ed58-4f18-b118-2a9f019e3af9', 'La Banque du Canada a annoncé une hausse de son taux directeur, le portant à 4,75%, une décision qui vise à contrer l''inflation persistante qui oscille autour de 3,5%. Cette augmentation, la quatrième en douze mois, aura des répercussions considérables sur les ménages canadiens, particulièrement ceux détenant un prêt hypothécaire à taux variable. Les économistes s''attendent à ce que le marché immobilier, déjà affecté par une baisse d''activité de 15% par rapport à l''année précédente, subisse un ralentissement supplémentaire. Par ailleurs, les entreprises qui dépendent du crédit pour financer leur expansion pourraient devoir revoir leurs plans d''investissement à la baisse. Cependant, la vigueur du marché du travail, avec un taux de chômage historiquement bas de 5,1%, pourrait atténuer l''impact de cette politique monétaire restrictive.

Question : Quels ménages seront particulièrement touchés par cette hausse ?', NULL, NULL, '["Ceux qui ont un pr\u00eat hypoth\u00e9caire \u00e0 taux variable", "Les familles nombreuses", "Les \u00e9tudiants", "Les retrait\u00e9s"]', 'Ceux qui ont un prêt hypothécaire à taux variable', '''Ceux qui ont un prêt hypothécaire à taux variable'' est la réponse correcte d''après le texte fourni.', 1, 9, '2026-07-18T04:12:22.152073'),
('eeca232b-2796-41ee-b6af-f310f745e9f0', 'a2288c0d-ed58-4f18-b118-2a9f019e3af9', 'La Banque du Canada a annoncé une hausse de son taux directeur, le portant à 4,75%, une décision qui vise à contrer l''inflation persistante qui oscille autour de 3,5%. Cette augmentation, la quatrième en douze mois, aura des répercussions considérables sur les ménages canadiens, particulièrement ceux détenant un prêt hypothécaire à taux variable. Les économistes s''attendent à ce que le marché immobilier, déjà affecté par une baisse d''activité de 15% par rapport à l''année précédente, subisse un ralentissement supplémentaire. Par ailleurs, les entreprises qui dépendent du crédit pour financer leur expansion pourraient devoir revoir leurs plans d''investissement à la baisse. Cependant, la vigueur du marché du travail, avec un taux de chômage historiquement bas de 5,1%, pourrait atténuer l''impact de cette politique monétaire restrictive.

Question : Quel est le taux de chômage actuel mentionné dans le texte ?', NULL, NULL, '["3,5%", "4,75%", "5,1%", "6,5%"]', '5,1%', '''5,1%'' est la réponse correcte d''après le texte fourni.', 1, 10, '2026-07-18T04:12:22.152085'),
('0f695ccf-42e6-43e4-8e01-20e11d52ac67', 'a2288c0d-ed58-4f18-b118-2a9f019e3af9', 'La Banque du Canada a annoncé une hausse de son taux directeur, le portant à 4,75%, une décision qui vise à contrer l''inflation persistante qui oscille autour de 3,5%. Cette augmentation, la quatrième en douze mois, aura des répercussions considérables sur les ménages canadiens, particulièrement ceux détenant un prêt hypothécaire à taux variable. Les économistes s''attendent à ce que le marché immobilier, déjà affecté par une baisse d''activité de 15% par rapport à l''année précédente, subisse un ralentissement supplémentaire. Par ailleurs, les entreprises qui dépendent du crédit pour financer leur expansion pourraient devoir revoir leurs plans d''investissement à la baisse. Cependant, la vigueur du marché du travail, avec un taux de chômage historiquement bas de 5,1%, pourrait atténuer l''impact de cette politique monétaire restrictive.

Question : Quel est l''impact sur le marché immobilier ?', NULL, NULL, '["Une augmentation des prix de 15%", "Un ralentissement suppl\u00e9mentaire", "Une stabilisation des prix", "Une reprise rapide"]', 'Un ralentissement supplémentaire', '''Un ralentissement supplémentaire'' est la réponse correcte d''après le texte fourni.', 1, 11, '2026-07-18T04:12:22.152095'),
('4b7c98a4-8c6e-4003-a9c5-981a9231228f', '54f063d3-a352-4e1b-b8cd-95fe076c9153', 'Bonjour et bienvenue à notre émission « Économie et Société ». Aujourd''hui, nous recevons le professeur Legrand, expert en politiques migratoires à l''Université de Montréal. Nous allons aborder la question de l''intégration des immigrants sur le marché du travail québécois, un sujet qui suscite de nombreux débats au sein de la classe politique. Professeur, selon vous, quelles sont les principales difficultés rencontrées par les nouveaux arrivants ?

Question : Quel est le sujet de l''émission radio ?', NULL, NULL, '["L''\u00e9conomie canadienne", "L''int\u00e9gration des immigrants sur le march\u00e9 du travail", "Les politiques \u00e9ducatives au Qu\u00e9bec", "Le syst\u00e8me de sant\u00e9 montr\u00e9alais"]', 'L''intégration des immigrants sur le marché du travail', '''L''intégration des immigrants sur le marché du travail'' est la réponse correcte d''après l''enregistrement audio.', 1, 0, '2026-07-18T04:12:22.152112'),
('c1ab66e0-a265-4aa4-be47-29a326f8de72', '54f063d3-a352-4e1b-b8cd-95fe076c9153', 'Bonjour et bienvenue à notre émission « Économie et Société ». Aujourd''hui, nous recevons le professeur Legrand, expert en politiques migratoires à l''Université de Montréal. Nous allons aborder la question de l''intégration des immigrants sur le marché du travail québécois, un sujet qui suscite de nombreux débats au sein de la classe politique. Professeur, selon vous, quelles sont les principales difficultés rencontrées par les nouveaux arrivants ?

Question : Qui est l''invité de l''émission ?', NULL, NULL, '["Un \u00e9conomiste", "Un professeur expert en politiques migratoires", "Un ministre du gouvernement", "Un chef d''entreprise"]', 'Un professeur expert en politiques migratoires', '''Un professeur expert en politiques migratoires'' est la réponse correcte d''après l''enregistrement audio.', 1, 1, '2026-07-18T04:12:22.152304'),
('e5dabb3c-c40f-45a9-a51b-68d70a61e421', '54f063d3-a352-4e1b-b8cd-95fe076c9153', 'Nous interrompons notre programme pour une information de dernière minute. La compagnie des wagons-lits et du tourisme (CWT) a annoncé ce matin une grève illimitée à compter de jeudi prochain, minuit. Le mouvement concerne l''ensemble du personnel roulant, soit près de 800 employés. Les négociations salariales, qui duraient depuis trois mois, ont échoué hier soir. La direction s''est dite « déçue » de cette issue et espère une reprise rapide du dialogue social. En attendant, les voyageurs sont invités à consulter le site internet de la société pour connaître les perturbations prévues sur leur ligne.

Question : Quel type de mouvement social est annoncé ?', NULL, NULL, '["Une manifestation", "Une gr\u00e8ve illimit\u00e9e", "Un d\u00e9brayage d''une journ\u00e9e", "Un lock-out"]', 'Une grève illimitée', '''Une grève illimitée'' est la réponse correcte d''après l''enregistrement audio.', 1, 2, '2026-07-18T04:12:22.152325'),
('343e0366-cbae-4b57-b196-7beb33b5a5b7', '54f063d3-a352-4e1b-b8cd-95fe076c9153', 'Nous interrompons notre programme pour une information de dernière minute. La compagnie des wagons-lits et du tourisme (CWT) a annoncé ce matin une grève illimitée à compter de jeudi prochain, minuit. Le mouvement concerne l''ensemble du personnel roulant, soit près de 800 employés. Les négociations salariales, qui duraient depuis trois mois, ont échoué hier soir. La direction s''est dite « déçue » de cette issue et espère une reprise rapide du dialogue social. En attendant, les voyageurs sont invités à consulter le site internet de la société pour connaître les perturbations prévues sur leur ligne.

Question : Combien d''employés sont concernés par ce mouvement ?', NULL, NULL, '["300", "500", "800", "1000"]', '800', '''800'' est la réponse correcte d''après l''enregistrement audio.', 1, 3, '2026-07-18T04:12:22.152334'),
('80b2f23c-9ef8-4194-9f79-1731141d39aa', '54f063d3-a352-4e1b-b8cd-95fe076c9153', 'Le ministère de l''Éducation nationale a dévoilé aujourd''hui son nouveau programme de réforme du baccalauréat. Parmi les changements majeurs, on note la suppression des filières générales existantes au profit d''un tronc commun renforcé et de spécialités à choisir dès la première. Les épreuves finales ne compteront plus que pour 60% de la note totale, le reste étant attribué au contrôle continu. Cette réforme, qui entrera en vigueur à la rentrée prochaine, suscite des réactions contrastées. Si certains syndicats enseignants saluent une modernisation nécessaire, d''autres dénoncent une réforme précipitée qui risque d''accroître les inégalités territoriales.

Question : Quel est le changement majeur concernant les filières ?', NULL, NULL, '["La suppression des fili\u00e8res existantes au profit de sp\u00e9cialit\u00e9s", "Le retour aux fili\u00e8res classiques", "L''ajout d''une nouvelle fili\u00e8re technologique", "La fusion de toutes les fili\u00e8res en une seule"]', 'La suppression des filières existantes au profit de spécialités', '''La suppression des filières existantes au profit de spécialités'' est la réponse correcte d''après l''enregistrement audio.', 1, 4, '2026-07-18T04:12:22.152344'),
('9c34f2bb-f715-4849-b1ea-ac887be5b5a7', '54f063d3-a352-4e1b-b8cd-95fe076c9153', 'Le ministère de l''Éducation nationale a dévoilé aujourd''hui son nouveau programme de réforme du baccalauréat. Parmi les changements majeurs, on note la suppression des filières générales existantes au profit d''un tronc commun renforcé et de spécialités à choisir dès la première. Les épreuves finales ne compteront plus que pour 60% de la note totale, le reste étant attribué au contrôle continu. Cette réforme, qui entrera en vigueur à la rentrée prochaine, suscite des réactions contrastées. Si certains syndicats enseignants saluent une modernisation nécessaire, d''autres dénoncent une réforme précipitée qui risque d''accroître les inégalités territoriales.

Question : Quel pourcentage de la note finale sera attribué au contrôle continu ?', NULL, NULL, '["30%", "40%", "50%", "60%"]', '40%', '''40%'' est la réponse correcte d''après l''enregistrement audio.', 1, 5, '2026-07-18T04:12:22.152351'),
('9f096869-ecfb-45c2-944e-b2c17fffe43e', '9021506f-d97d-4181-98c5-275916405ee2', 'Le gouvernement canadien a récemment dévoilé son plan d''action national pour la transition écologique, un document de 150 pages qui fixe des objectifs ambitieux pour réduire les émissions de gaz à effet de serre de 45% d''ici 2030 par rapport aux niveaux de 2005. Ce plan, qui s''inscrit dans le cadre de l''Accord de Paris, prévoit des investissements majeurs dans les énergies renouvelables, l''électrification des transports et l''efficacité énergétique des bâtiments. Parmi les mesures phares, on trouve l''installation de bornes de recharge pour véhicules électriques sur l''ensemble du territoire, des subventions pour la rénovation énergétique des logements anciens, et un soutien accru à la recherche et développement dans le secteur des technologies vertes. Le gouvernement estime que ces mesures pourraient créer jusqu''à 200 000 emplois dans les prochaines années. Cependant, ce plan fait face à des critiques. Certains groupes environnementaux estiment que les objectifs ne sont pas assez ambitieux, tandis que des représentants du secteur pétrolier s''inquiètent des conséquences économiques pour les régions dépendantes des hydrocarbures.

Question : Quel est l''objectif principal du plan d''action national pour la transition écologique ?', NULL, NULL, '["R\u00e9duire les \u00e9missions de GES de 45% d''ici 2030", "\u00c9liminer compl\u00e8tement les hydrocarbures d''ici 2030", "Cr\u00e9er 500 000 emplois verts", "Atteindre la neutralit\u00e9 carbone en 2025"]', 'Réduire les émissions de GES de 45% d''ici 2030', '''Réduire les émissions de GES de 45% d''ici 2030'' est la réponse correcte d''après le texte fourni.', 1, 0, '2026-07-18T04:12:22.152369'),
('a125d273-9937-4329-8ddc-ad4cd540001e', '9021506f-d97d-4181-98c5-275916405ee2', 'Le gouvernement canadien a récemment dévoilé son plan d''action national pour la transition écologique, un document de 150 pages qui fixe des objectifs ambitieux pour réduire les émissions de gaz à effet de serre de 45% d''ici 2030 par rapport aux niveaux de 2005. Ce plan, qui s''inscrit dans le cadre de l''Accord de Paris, prévoit des investissements majeurs dans les énergies renouvelables, l''électrification des transports et l''efficacité énergétique des bâtiments. Parmi les mesures phares, on trouve l''installation de bornes de recharge pour véhicules électriques sur l''ensemble du territoire, des subventions pour la rénovation énergétique des logements anciens, et un soutien accru à la recherche et développement dans le secteur des technologies vertes. Le gouvernement estime que ces mesures pourraient créer jusqu''à 200 000 emplois dans les prochaines années. Cependant, ce plan fait face à des critiques. Certains groupes environnementaux estiment que les objectifs ne sont pas assez ambitieux, tandis que des représentants du secteur pétrolier s''inquiètent des conséquences économiques pour les régions dépendantes des hydrocarbures.

Question : Quelles sont les mesures phares mentionnées dans le plan ?', NULL, NULL, '["L''installation de bornes de recharge, des subventions pour la r\u00e9novation, et le soutien \u00e0 la R&D", "La construction de nouvelles centrales nucl\u00e9aires et l''exportation de p\u00e9trole", "L''interdiction totale des v\u00e9hicules thermiques et la taxation du carbone", "La fermeture des industries polluantes et la d\u00e9localisation"]', 'L''installation de bornes de recharge, des subventions pour la rénovation, et le soutien à la R&D', '''L''installation de bornes de recharge, des subventions pour la rénovation, et le soutien à la R&D'' est la réponse correcte d''après le texte fourni.', 1, 1, '2026-07-18T04:12:22.152378'),
('b81b9b04-f6ac-4133-be99-bda5c75163aa', '9021506f-d97d-4181-98c5-275916405ee2', 'Le gouvernement canadien a récemment dévoilé son plan d''action national pour la transition écologique, un document de 150 pages qui fixe des objectifs ambitieux pour réduire les émissions de gaz à effet de serre de 45% d''ici 2030 par rapport aux niveaux de 2005. Ce plan, qui s''inscrit dans le cadre de l''Accord de Paris, prévoit des investissements majeurs dans les énergies renouvelables, l''électrification des transports et l''efficacité énergétique des bâtiments. Parmi les mesures phares, on trouve l''installation de bornes de recharge pour véhicules électriques sur l''ensemble du territoire, des subventions pour la rénovation énergétique des logements anciens, et un soutien accru à la recherche et développement dans le secteur des technologies vertes. Le gouvernement estime que ces mesures pourraient créer jusqu''à 200 000 emplois dans les prochaines années. Cependant, ce plan fait face à des critiques. Certains groupes environnementaux estiment que les objectifs ne sont pas assez ambitieux, tandis que des représentants du secteur pétrolier s''inquiètent des conséquences économiques pour les régions dépendantes des hydrocarbures.

Question : Combien d''emplois ces mesures pourraient-elles créer selon le gouvernement ?', NULL, NULL, '["50 000", "100 000", "200 000", "500 000"]', '200 000', '''200 000'' est la réponse correcte d''après le texte fourni.', 1, 2, '2026-07-18T04:12:22.152386'),
('71549d11-50bd-4333-882e-044157a172d9', '9021506f-d97d-4181-98c5-275916405ee2', 'Le gouvernement canadien a récemment dévoilé son plan d''action national pour la transition écologique, un document de 150 pages qui fixe des objectifs ambitieux pour réduire les émissions de gaz à effet de serre de 45% d''ici 2030 par rapport aux niveaux de 2005. Ce plan, qui s''inscrit dans le cadre de l''Accord de Paris, prévoit des investissements majeurs dans les énergies renouvelables, l''électrification des transports et l''efficacité énergétique des bâtiments. Parmi les mesures phares, on trouve l''installation de bornes de recharge pour véhicules électriques sur l''ensemble du territoire, des subventions pour la rénovation énergétique des logements anciens, et un soutien accru à la recherche et développement dans le secteur des technologies vertes. Le gouvernement estime que ces mesures pourraient créer jusqu''à 200 000 emplois dans les prochaines années. Cependant, ce plan fait face à des critiques. Certains groupes environnementaux estiment que les objectifs ne sont pas assez ambitieux, tandis que des représentants du secteur pétrolier s''inquiètent des conséquences économiques pour les régions dépendantes des hydrocarbures.

Question : Quelles sont les principales critiques adressées à ce plan ?', NULL, NULL, '["Il est trop ambitieux pour certains et pas assez pour d''autres", "Il est unanimement soutenu par tous les partis", "Il manque totalement de financement", "Il est jug\u00e9 inconstitutionnel"]', 'Il est trop ambitieux pour certains et pas assez pour d''autres', '''Il est trop ambitieux pour certains et pas assez pour d''autres'' est la réponse correcte d''après le texte fourni.', 1, 3, '2026-07-18T04:12:22.152393'),
('c643bd23-b417-499e-90b8-48a5a03bcac4', '9021506f-d97d-4181-98c5-275916405ee2', 'L''immigration joue un rôle fondamental dans le développement économique et démographique du Canada. Selon les données publiées par Statistique Canada, le pays a accueilli plus de 430 000 nouveaux résidents permanents en 2023, un chiffre record qui témoigne de la politique d''immigration ambitieuse du gouvernement fédéral. Les provinces qui ont connu la plus forte croissance démographique sont l''Ontario, la Colombie-Britannique et l''Alberta. Les nouveaux arrivants s''installent majoritairement dans les grands centres urbains comme Toronto, Vancouver et Montréal, attirés par les opportunités d''emploi et les services d''établissement. Le système de gestion des demandes d''immigration, basé sur le système de points Entrée express, a été conçu pour attirer des travailleurs qualifiés capables de contribuer rapidement à l''économie canadienne. Les critères de sélection prennent en compte l''âge, le niveau d''éducation, l''expérience professionnelle, les compétences linguistiques en français et en anglais, ainsi que la capacité d''adaptation. « L''immigration n''est pas seulement une nécessité économique, c''est aussi une source d''enrichissement culturel, » a souligné le ministre.

Question : Combien de nouveaux résidents permanents le Canada a-t-il accueilli en 2023 ?', NULL, NULL, '["Plus de 200 000", "Plus de 300 000", "Plus de 430 000", "Plus de 500 000"]', 'Plus de 430 000', '''Plus de 430 000'' est la réponse correcte d''après le texte fourni.', 1, 4, '2026-07-18T04:12:22.152402'),
('1766c42b-a73b-4069-9905-8c85d05880f5', '9021506f-d97d-4181-98c5-275916405ee2', 'L''immigration joue un rôle fondamental dans le développement économique et démographique du Canada. Selon les données publiées par Statistique Canada, le pays a accueilli plus de 430 000 nouveaux résidents permanents en 2023, un chiffre record qui témoigne de la politique d''immigration ambitieuse du gouvernement fédéral. Les provinces qui ont connu la plus forte croissance démographique sont l''Ontario, la Colombie-Britannique et l''Alberta. Les nouveaux arrivants s''installent majoritairement dans les grands centres urbains comme Toronto, Vancouver et Montréal, attirés par les opportunités d''emploi et les services d''établissement. Le système de gestion des demandes d''immigration, basé sur le système de points Entrée express, a été conçu pour attirer des travailleurs qualifiés capables de contribuer rapidement à l''économie canadienne. Les critères de sélection prennent en compte l''âge, le niveau d''éducation, l''expérience professionnelle, les compétences linguistiques en français et en anglais, ainsi que la capacité d''adaptation. « L''immigration n''est pas seulement une nécessité économique, c''est aussi une source d''enrichissement culturel, » a souligné le ministre.

Question : Quelles provinces ont connu la plus forte croissance démographique ?', NULL, NULL, '["Le Qu\u00e9bec et les provinces maritimes", "L''Ontario, la Colombie-Britannique et l''Alberta", "Le Manitoba, la Saskatchewan et les Territoires", "La Nouvelle-\u00c9cosse et Terre-Neuve"]', 'L''Ontario, la Colombie-Britannique et l''Alberta', '''L''Ontario, la Colombie-Britannique et l''Alberta'' est la réponse correcte d''après le texte fourni.', 1, 5, '2026-07-18T04:12:22.152409'),
('08ca045e-316b-455e-bf7f-c6349e719462', '9021506f-d97d-4181-98c5-275916405ee2', 'L''immigration joue un rôle fondamental dans le développement économique et démographique du Canada. Selon les données publiées par Statistique Canada, le pays a accueilli plus de 430 000 nouveaux résidents permanents en 2023, un chiffre record qui témoigne de la politique d''immigration ambitieuse du gouvernement fédéral. Les provinces qui ont connu la plus forte croissance démographique sont l''Ontario, la Colombie-Britannique et l''Alberta. Les nouveaux arrivants s''installent majoritairement dans les grands centres urbains comme Toronto, Vancouver et Montréal, attirés par les opportunités d''emploi et les services d''établissement. Le système de gestion des demandes d''immigration, basé sur le système de points Entrée express, a été conçu pour attirer des travailleurs qualifiés capables de contribuer rapidement à l''économie canadienne. Les critères de sélection prennent en compte l''âge, le niveau d''éducation, l''expérience professionnelle, les compétences linguistiques en français et en anglais, ainsi que la capacité d''adaptation. « L''immigration n''est pas seulement une nécessité économique, c''est aussi une source d''enrichissement culturel, » a souligné le ministre.

Question : Comment le système Entrée express sélectionne-t-il les candidats ?', NULL, NULL, '["Par tirage au sort", "Sur la base d''un syst\u00e8me de points incluant \u00e2ge, \u00e9ducation, exp\u00e9rience et langues", "Par ordre d''arriv\u00e9e des demandes", "Uniquement sur la base des comp\u00e9tences linguistiques"]', 'Sur la base d''un système de points incluant âge, éducation, expérience et langues', '''Sur la base d''un système de points incluant âge, éducation, expérience et langues'' est la réponse correcte d''après le texte fourni.', 1, 6, '2026-07-18T04:12:22.152417'),
('e8c5d94e-341f-487e-b24d-85b26c20bd44', '9021506f-d97d-4181-98c5-275916405ee2', 'L''immigration joue un rôle fondamental dans le développement économique et démographique du Canada. Selon les données publiées par Statistique Canada, le pays a accueilli plus de 430 000 nouveaux résidents permanents en 2023, un chiffre record qui témoigne de la politique d''immigration ambitieuse du gouvernement fédéral. Les provinces qui ont connu la plus forte croissance démographique sont l''Ontario, la Colombie-Britannique et l''Alberta. Les nouveaux arrivants s''installent majoritairement dans les grands centres urbains comme Toronto, Vancouver et Montréal, attirés par les opportunités d''emploi et les services d''établissement. Le système de gestion des demandes d''immigration, basé sur le système de points Entrée express, a été conçu pour attirer des travailleurs qualifiés capables de contribuer rapidement à l''économie canadienne. Les critères de sélection prennent en compte l''âge, le niveau d''éducation, l''expérience professionnelle, les compétences linguistiques en français et en anglais, ainsi que la capacité d''adaptation. « L''immigration n''est pas seulement une nécessité économique, c''est aussi une source d''enrichissement culturel, » a souligné le ministre.

Question : Quels sont les défis persistants mentionnés ?', NULL, NULL, '["L''int\u00e9gration professionnelle, le logement abordable et la reconnaissance des dipl\u00f4mes", "Le climat, les infrastructures et les transports", "La s\u00e9curit\u00e9, l''\u00e9ducation et la sant\u00e9", "L''imp\u00f4t, la retraite et les assurances"]', 'L''intégration professionnelle, le logement abordable et la reconnaissance des diplômes', '''L''intégration professionnelle, le logement abordable et la reconnaissance des diplômes'' est la réponse correcte d''après le texte fourni.', 1, 7, '2026-07-18T04:12:22.152426'),
('2fd9832e-d1bb-46fc-98c0-4edf8b9aa1d2', '9021506f-d97d-4181-98c5-275916405ee2', 'La Banque du Canada a annoncé une hausse de son taux directeur, le portant à 4,75%, une décision qui vise à contrer l''inflation persistante qui oscille autour de 3,5%. Cette augmentation, la quatrième en douze mois, aura des répercussions considérables sur les ménages canadiens, particulièrement ceux détenant un prêt hypothécaire à taux variable. Les économistes s''attendent à ce que le marché immobilier, déjà affecté par une baisse d''activité de 15% par rapport à l''année précédente, subisse un ralentissement supplémentaire. Par ailleurs, les entreprises qui dépendent du crédit pour financer leur expansion pourraient devoir revoir leurs plans d''investissement à la baisse. Cependant, la vigueur du marché du travail, avec un taux de chômage historiquement bas de 5,1%, pourrait atténuer l''impact de cette politique monétaire restrictive.

Question : Quel est le nouveau taux directeur annoncé par la Banque du Canada ?', NULL, NULL, '["3,5%", "4,75%", "5,1%", "6%"]', '4,75%', '''4,75%'' est la réponse correcte d''après le texte fourni.', 1, 8, '2026-07-18T04:12:22.152433'),
('9b06900b-ebed-42dc-8ef3-40e4ca8e834b', '9021506f-d97d-4181-98c5-275916405ee2', 'La Banque du Canada a annoncé une hausse de son taux directeur, le portant à 4,75%, une décision qui vise à contrer l''inflation persistante qui oscille autour de 3,5%. Cette augmentation, la quatrième en douze mois, aura des répercussions considérables sur les ménages canadiens, particulièrement ceux détenant un prêt hypothécaire à taux variable. Les économistes s''attendent à ce que le marché immobilier, déjà affecté par une baisse d''activité de 15% par rapport à l''année précédente, subisse un ralentissement supplémentaire. Par ailleurs, les entreprises qui dépendent du crédit pour financer leur expansion pourraient devoir revoir leurs plans d''investissement à la baisse. Cependant, la vigueur du marché du travail, avec un taux de chômage historiquement bas de 5,1%, pourrait atténuer l''impact de cette politique monétaire restrictive.

Question : Quels ménages seront particulièrement touchés par cette hausse ?', NULL, NULL, '["Ceux qui ont un pr\u00eat hypoth\u00e9caire \u00e0 taux variable", "Les familles nombreuses", "Les \u00e9tudiants", "Les retrait\u00e9s"]', 'Ceux qui ont un prêt hypothécaire à taux variable', '''Ceux qui ont un prêt hypothécaire à taux variable'' est la réponse correcte d''après le texte fourni.', 1, 9, '2026-07-18T04:12:22.152439'),
('b7a5025d-0784-432d-9a15-9fba6aa18a73', '9021506f-d97d-4181-98c5-275916405ee2', 'La Banque du Canada a annoncé une hausse de son taux directeur, le portant à 4,75%, une décision qui vise à contrer l''inflation persistante qui oscille autour de 3,5%. Cette augmentation, la quatrième en douze mois, aura des répercussions considérables sur les ménages canadiens, particulièrement ceux détenant un prêt hypothécaire à taux variable. Les économistes s''attendent à ce que le marché immobilier, déjà affecté par une baisse d''activité de 15% par rapport à l''année précédente, subisse un ralentissement supplémentaire. Par ailleurs, les entreprises qui dépendent du crédit pour financer leur expansion pourraient devoir revoir leurs plans d''investissement à la baisse. Cependant, la vigueur du marché du travail, avec un taux de chômage historiquement bas de 5,1%, pourrait atténuer l''impact de cette politique monétaire restrictive.

Question : Quel est le taux de chômage actuel mentionné dans le texte ?', NULL, NULL, '["3,5%", "4,75%", "5,1%", "6,5%"]', '5,1%', '''5,1%'' est la réponse correcte d''après le texte fourni.', 1, 10, '2026-07-18T04:12:22.152452'),
('bb6bebbc-2c39-4498-9bbe-5bcc6c8d7e86', '9021506f-d97d-4181-98c5-275916405ee2', 'La Banque du Canada a annoncé une hausse de son taux directeur, le portant à 4,75%, une décision qui vise à contrer l''inflation persistante qui oscille autour de 3,5%. Cette augmentation, la quatrième en douze mois, aura des répercussions considérables sur les ménages canadiens, particulièrement ceux détenant un prêt hypothécaire à taux variable. Les économistes s''attendent à ce que le marché immobilier, déjà affecté par une baisse d''activité de 15% par rapport à l''année précédente, subisse un ralentissement supplémentaire. Par ailleurs, les entreprises qui dépendent du crédit pour financer leur expansion pourraient devoir revoir leurs plans d''investissement à la baisse. Cependant, la vigueur du marché du travail, avec un taux de chômage historiquement bas de 5,1%, pourrait atténuer l''impact de cette politique monétaire restrictive.

Question : Quel est l''impact sur le marché immobilier ?', NULL, NULL, '["Une augmentation des prix de 15%", "Un ralentissement suppl\u00e9mentaire", "Une stabilisation des prix", "Une reprise rapide"]', 'Un ralentissement supplémentaire', '''Un ralentissement supplémentaire'' est la réponse correcte d''après le texte fourni.', 1, 11, '2026-07-18T04:12:22.152464'),
('90f9a4b3-0f0e-4e8d-bfc8-e4b5b7096826', '85f94a53-c5ee-490b-8f83-901082764b10', 'Bonjour et bienvenue à notre émission « Économie et Société ». Aujourd''hui, nous recevons le professeur Legrand, expert en politiques migratoires à l''Université de Montréal. Nous allons aborder la question de l''intégration des immigrants sur le marché du travail québécois, un sujet qui suscite de nombreux débats au sein de la classe politique. Professeur, selon vous, quelles sont les principales difficultés rencontrées par les nouveaux arrivants ?

Question : Quel est le sujet de l''émission radio ?', NULL, NULL, '["L''\u00e9conomie canadienne", "L''int\u00e9gration des immigrants sur le march\u00e9 du travail", "Les politiques \u00e9ducatives au Qu\u00e9bec", "Le syst\u00e8me de sant\u00e9 montr\u00e9alais"]', 'L''intégration des immigrants sur le marché du travail', '''L''intégration des immigrants sur le marché du travail'' est la réponse correcte d''après l''enregistrement audio.', 1, 0, '2026-07-18T04:12:22.152492'),
('8a3b2cb4-b678-45d8-8c87-bb20b2e4a708', '85f94a53-c5ee-490b-8f83-901082764b10', 'Bonjour et bienvenue à notre émission « Économie et Société ». Aujourd''hui, nous recevons le professeur Legrand, expert en politiques migratoires à l''Université de Montréal. Nous allons aborder la question de l''intégration des immigrants sur le marché du travail québécois, un sujet qui suscite de nombreux débats au sein de la classe politique. Professeur, selon vous, quelles sont les principales difficultés rencontrées par les nouveaux arrivants ?

Question : Qui est l''invité de l''émission ?', NULL, NULL, '["Un \u00e9conomiste", "Un professeur expert en politiques migratoires", "Un ministre du gouvernement", "Un chef d''entreprise"]', 'Un professeur expert en politiques migratoires', '''Un professeur expert en politiques migratoires'' est la réponse correcte d''après l''enregistrement audio.', 1, 1, '2026-07-18T04:12:22.152505'),
('345dcc5d-0f64-478e-bd69-269bff741b6d', '85f94a53-c5ee-490b-8f83-901082764b10', 'Nous interrompons notre programme pour une information de dernière minute. La compagnie des wagons-lits et du tourisme (CWT) a annoncé ce matin une grève illimitée à compter de jeudi prochain, minuit. Le mouvement concerne l''ensemble du personnel roulant, soit près de 800 employés. Les négociations salariales, qui duraient depuis trois mois, ont échoué hier soir. La direction s''est dite « déçue » de cette issue et espère une reprise rapide du dialogue social. En attendant, les voyageurs sont invités à consulter le site internet de la société pour connaître les perturbations prévues sur leur ligne.

Question : Quel type de mouvement social est annoncé ?', NULL, NULL, '["Une manifestation", "Une gr\u00e8ve illimit\u00e9e", "Un d\u00e9brayage d''une journ\u00e9e", "Un lock-out"]', 'Une grève illimitée', '''Une grève illimitée'' est la réponse correcte d''après l''enregistrement audio.', 1, 2, '2026-07-18T04:12:22.152521'),
('a30983d3-11db-4644-a80f-ba6c14b03d8f', '85f94a53-c5ee-490b-8f83-901082764b10', 'Nous interrompons notre programme pour une information de dernière minute. La compagnie des wagons-lits et du tourisme (CWT) a annoncé ce matin une grève illimitée à compter de jeudi prochain, minuit. Le mouvement concerne l''ensemble du personnel roulant, soit près de 800 employés. Les négociations salariales, qui duraient depuis trois mois, ont échoué hier soir. La direction s''est dite « déçue » de cette issue et espère une reprise rapide du dialogue social. En attendant, les voyageurs sont invités à consulter le site internet de la société pour connaître les perturbations prévues sur leur ligne.

Question : Combien d''employés sont concernés par ce mouvement ?', NULL, NULL, '["300", "500", "800", "1000"]', '800', '''800'' est la réponse correcte d''après l''enregistrement audio.', 1, 3, '2026-07-18T04:12:22.152532'),
('1b80f138-48f4-441f-a024-b55b5bdbfd90', '85f94a53-c5ee-490b-8f83-901082764b10', 'Le ministère de l''Éducation nationale a dévoilé aujourd''hui son nouveau programme de réforme du baccalauréat. Parmi les changements majeurs, on note la suppression des filières générales existantes au profit d''un tronc commun renforcé et de spécialités à choisir dès la première. Les épreuves finales ne compteront plus que pour 60% de la note totale, le reste étant attribué au contrôle continu. Cette réforme, qui entrera en vigueur à la rentrée prochaine, suscite des réactions contrastées. Si certains syndicats enseignants saluent une modernisation nécessaire, d''autres dénoncent une réforme précipitée qui risque d''accroître les inégalités territoriales.

Question : Quel est le changement majeur concernant les filières ?', NULL, NULL, '["La suppression des fili\u00e8res existantes au profit de sp\u00e9cialit\u00e9s", "Le retour aux fili\u00e8res classiques", "L''ajout d''une nouvelle fili\u00e8re technologique", "La fusion de toutes les fili\u00e8res en une seule"]', 'La suppression des filières existantes au profit de spécialités', '''La suppression des filières existantes au profit de spécialités'' est la réponse correcte d''après l''enregistrement audio.', 1, 4, '2026-07-18T04:12:22.152545'),
('b8482b50-3ef8-42f8-8183-d6af8821af6d', '85f94a53-c5ee-490b-8f83-901082764b10', 'Le ministère de l''Éducation nationale a dévoilé aujourd''hui son nouveau programme de réforme du baccalauréat. Parmi les changements majeurs, on note la suppression des filières générales existantes au profit d''un tronc commun renforcé et de spécialités à choisir dès la première. Les épreuves finales ne compteront plus que pour 60% de la note totale, le reste étant attribué au contrôle continu. Cette réforme, qui entrera en vigueur à la rentrée prochaine, suscite des réactions contrastées. Si certains syndicats enseignants saluent une modernisation nécessaire, d''autres dénoncent une réforme précipitée qui risque d''accroître les inégalités territoriales.

Question : Quel pourcentage de la note finale sera attribué au contrôle continu ?', NULL, NULL, '["30%", "40%", "50%", "60%"]', '40%', '''40%'' est la réponse correcte d''après l''enregistrement audio.', 1, 5, '2026-07-18T04:12:22.152556'),
('2ded54cd-874a-441c-946d-1cbe6e2e99a2', 'c07e56de-6700-4461-8ce4-e7f8005fe8f1', '### Section A : Courrier formel

En tant que président d''une association de quartier, vous écrivez au maire de votre ville pour lui soumettre une proposition d''aménagement d''un espace vert sur un terrain vacant. Présentez les avantages de votre projet pour la communauté et les étapes de sa réalisation. (200-250 mots)', NULL, NULL, NULL, NULL, 'Utilisez un vocabulaire soutenu, des structures complexes et une argumentation structurée.', 10, 0, '2026-07-18T04:12:22.152584'),
('444fc648-40ce-4a35-b30e-463d49ca3917', 'c07e56de-6700-4461-8ce4-e7f8005fe8f1', '### Section B : Article argumentatif

Rédigez un article pour le journal de votre université dans lequel vous analysez les impacts de l''intelligence artificielle sur le marché du travail. Vous présenterez les opportunités et les risques, et proposerez des pistes pour une transition harmonieuse. (250-300 mots)', NULL, NULL, NULL, NULL, 'Utilisez un vocabulaire soutenu, des structures complexes et une argumentation structurée.', 10, 1, '2026-07-18T04:12:22.152593'),
('c2ccaf87-6a2a-457c-b935-c33760ec95fa', 'c6ee9da4-4898-43c1-a660-4e33a8c1311c', '### Section A : Présentation et discussion

Vous participez à un entretien pour un poste de chef de projet dans une entreprise francophone. Présentez votre parcours professionnel, vos compétences et expliquez pourquoi vous êtes le candidat idéal. L''examinateur vous posera ensuite des questions sur vos expériences.', NULL, NULL, NULL, NULL, 'Structurez votre discours, utilisez des connecteurs logiques et variez le vocabulaire.', 10, 0, '2026-07-18T04:12:22.152612'),
('a55dae23-77f9-435a-91cc-70e09786455a', 'c6ee9da4-4898-43c1-a660-4e33a8c1311c', '### Section B : Débat argumenté

Votre ville souhaite instaurer une zone à faibles émissions interdisant les véhicules les plus polluants dans le centre-ville. Vous êtes invité à une réunion publique. Présentez votre position (pour ou contre) en argumentant de manière structurée et en répondant aux objections potentielles.', NULL, NULL, NULL, NULL, 'Structurez votre discours, utilisez des connecteurs logiques et variez le vocabulaire.', 10, 1, '2026-07-18T04:12:22.152617'),
('22249fd6-39de-430b-b7aa-3def0f15d455', 'dd264253-d558-466e-bf2b-79be230e08a2', '### Section A : Courrier formel

En tant que président d''une association de quartier, vous écrivez au maire de votre ville pour lui soumettre une proposition d''aménagement d''un espace vert sur un terrain vacant. Présentez les avantages de votre projet pour la communauté et les étapes de sa réalisation. (200-250 mots)', NULL, NULL, NULL, NULL, 'Utilisez un vocabulaire soutenu, des structures complexes et une argumentation structurée.', 10, 0, '2026-07-18T04:12:22.152636'),
('947da81c-b08f-450d-a4e7-377da9c4a45f', 'dd264253-d558-466e-bf2b-79be230e08a2', '### Section B : Article argumentatif

Rédigez un article pour le journal de votre université dans lequel vous analysez les impacts de l''intelligence artificielle sur le marché du travail. Vous présenterez les opportunités et les risques, et proposerez des pistes pour une transition harmonieuse. (250-300 mots)', NULL, NULL, NULL, NULL, 'Utilisez un vocabulaire soutenu, des structures complexes et une argumentation structurée.', 10, 1, '2026-07-18T04:12:22.152644'),
('ca6a5684-0a54-490a-b2f9-2781c8f6135e', 'b099f02b-bf61-48ff-b4f9-0c730d3a8d51', '### Section A : Présentation et discussion

Vous participez à un entretien pour un poste de chef de projet dans une entreprise francophone. Présentez votre parcours professionnel, vos compétences et expliquez pourquoi vous êtes le candidat idéal. L''examinateur vous posera ensuite des questions sur vos expériences.', NULL, NULL, NULL, NULL, 'Structurez votre discours, utilisez des connecteurs logiques et variez le vocabulaire.', 10, 0, '2026-07-18T04:12:22.152662'),
('55cb1a76-3e98-4745-8eec-1ee423ca1a98', 'b099f02b-bf61-48ff-b4f9-0c730d3a8d51', '### Section B : Débat argumenté

Votre ville souhaite instaurer une zone à faibles émissions interdisant les véhicules les plus polluants dans le centre-ville. Vous êtes invité à une réunion publique. Présentez votre position (pour ou contre) en argumentant de manière structurée et en répondant aux objections potentielles.', NULL, NULL, NULL, NULL, 'Structurez votre discours, utilisez des connecteurs logiques et variez le vocabulaire.', 10, 1, '2026-07-18T04:12:22.152669');