INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('87348e33-3c8a-48e9-8734-d9d093bed835', 'f61d727f-858f-42bf-93ef-72ad5fc0d77c', '### L''économie française face aux défis de la transition énergétique

La transition énergétique représente à la fois un défi et une opportunité pour l''économie française. Alors que le gouvernement a fixé l''objectif ambitieux d''atteindre la neutralité carbone d''ici 2050, les entreprises doivent désormais repenser leurs modèles d''affaires pour s''adapter à cette nouvelle donne. Encore faudrait-il que les investissements nécessaires suivent le rythme des ambitions affichées.

Selon un rapport récent de l''Observatoire des investissements verts, les montants alloués aux énergies renouvelables ont augmenté de 35% au cours des deux dernières années, témoignant d''une prise de conscience collective. Néanmoins, certains secteurs industriels, notamment l''automobile et la sidérurgie, peinent à opérer leur mue écologique sans compromettre leur compétitivité sur le marché international. Le président d''un grand groupe industriel a récemment déclaré qu''il serait indispensable que l''Union européenne assouplisse temporairement certaines normes environnementales pour permettre une transition en douceur.

Les économistes s''interrogent sur la capacité de la France à concilier impératifs écologiques et croissance économique. « Il faudrait que les pouvoirs publics accompagnent davantage les PME dans cette transition, car elles représentent le tissu économique le plus vulnérable », souligne une étude de la Banque de France. Les prochaines années seront décisives pour déterminer si cette transformation structurelle portera ses fruits, d''autant que la facture énergétique des ménages continue d''augmenter, ce qui suscite des inquiétudes quant à l''acceptabilité sociale de ces réformes.

Question : Quel est le thème central de cet article ?', NULL, '["Les défis économiques de la transition énergétique en France", "La fermeture des centrales nucléaires françaises", "Les nouvelles technologies de stockage d''énergie", "La concurrence commerciale entre la France et l''Allemagne"]', 'Les défis économiques de la transition énergétique en France', 1, 0, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('680b4fca-ca87-4794-b30b-0c52242720a6', 'f61d727f-858f-42bf-93ef-72ad5fc0d77c', '### Politique d''immigration au Canada : le français comme vecteur d''intégration

Le Canada renforce sa politique d''immigration francophone en dehors du Québec, avec l''objectif ambitieux d''atteindre 12% d''immigrants francophones d''ici 2028 dans les provinces et territoires anglophones. Cette stratégie, qui s''inscrit dans le cadre de la Loi sur les langues officielles, vise à contrer le déclin du poids démographique des communautés francophones hors Québec. Il est essentiel que les nouveaux arrivants puissent s''intégrer pleinement dans la société canadienne.

« La maîtrise du français constitue un atout indéniable pour les candidats à l''immigration, leur permettant d''accumuler des points supplémentaires dans le système Entrée express », rappelle une conseillère en immigration basée à Toronto. Les données officielles indiquent que les candidats francophones obtiennent en moyenne des scores plus élevés et que leur dossier est traité plus rapidement. Le gouvernement fédéral souhaite que les provinces collaborent davantage à la mise en œuvre de cette stratégie linguistique.

Les nouveaux arrivants francophones bénéficient par ailleurs de programmes d''accompagnement spécifiques, notamment des services d''établissement et des cours de perfectionnement linguistique. Cependant, des défis persistent, particulièrement en ce qui concerne l''accès à l''emploi dans leur domaine de compétence. Des associations militent pour que les diplômes étrangers soient mieux reconnus et que l''accompagnement vers l''intégration professionnelle soit renforcé. Selon une étude récente, 71% des immigrants francophones trouvent un emploi dans leur domaine dans les deux ans suivant leur arrivée, un chiffre encourageant mais qui pourrait encore être amélioré.

Question : Que peut-on déduire de l''avantage des candidats francophones dans le système Entrée express ?', NULL, '["Le français offre un avantage concret dans le processus de sélection", "Le français n''a aucun impact sur le score des candidats", "Seuls les candidats bilingues sont acceptés", "L''anglais est le seul critère linguistique pris en compte"]', 'Le français offre un avantage concret dans le processus de sélection', 1, 1, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('298ace14-a24f-4daa-a995-d50388262d07', 'f61d727f-858f-42bf-93ef-72ad5fc0d77c', '### Politique d''immigration au Canada : le français comme vecteur d''intégration

Le Canada renforce sa politique d''immigration francophone en dehors du Québec, avec l''objectif ambitieux d''atteindre 12% d''immigrants francophones d''ici 2028 dans les provinces et territoires anglophones. Cette stratégie, qui s''inscrit dans le cadre de la Loi sur les langues officielles, vise à contrer le déclin du poids démographique des communautés francophones hors Québec. Il est essentiel que les nouveaux arrivants puissent s''intégrer pleinement dans la société canadienne.

« La maîtrise du français constitue un atout indéniable pour les candidats à l''immigration, leur permettant d''accumuler des points supplémentaires dans le système Entrée express », rappelle une conseillère en immigration basée à Toronto. Les données officielles indiquent que les candidats francophones obtiennent en moyenne des scores plus élevés et que leur dossier est traité plus rapidement. Le gouvernement fédéral souhaite que les provinces collaborent davantage à la mise en œuvre de cette stratégie linguistique.

Les nouveaux arrivants francophones bénéficient par ailleurs de programmes d''accompagnement spécifiques, notamment des services d''établissement et des cours de perfectionnement linguistique. Cependant, des défis persistent, particulièrement en ce qui concerne l''accès à l''emploi dans leur domaine de compétence. Des associations militent pour que les diplômes étrangers soient mieux reconnus et que l''accompagnement vers l''intégration professionnelle soit renforcé. Selon une étude récente, 71% des immigrants francophones trouvent un emploi dans leur domaine dans les deux ans suivant leur arrivée, un chiffre encourageant mais qui pourrait encore être amélioré.

Question : Quel est le sujet principal de cet article ?', NULL, '["La politique d''immigration francophone au Canada et ses enjeux", "Les procédures de demande de visa pour le Canada", "La comparaison entre les systèmes d''immigration canadien et américain", "Les difficultés économiques du Québec"]', 'La politique d''immigration francophone au Canada et ses enjeux', 1, 2, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('358b5a91-88eb-4481-9334-e5853bdccda5', '907602a7-d59c-4ad7-bebd-96d3e95bcf7c', '### Vente de véhicule d''occasion

Berline hybride de 2021, 45 000 km, entretien exclusif en concession. Véhicule non-fumeur, toujours stationné en garage fermé. Équipements premium : toit ouvrant panoramique, aide au stationnement 360°, régulateur de vitesse adaptatif. Garantie constructeur encore valable 12 mois. Prix : 22 500 € à débattre dans la limite du raisonnable. Premier contact par courriel uniquement. Agences s''abstenir.

Question : Quel est le mode de propulsion du véhicule ?', NULL, '["Diesel", "Essence uniquement", "Hybride", "Électrique"]', 'Hybride', 1, 3, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('f1bf884f-795d-4c5f-98d3-e13b10c6f458', 'f61d727f-858f-42bf-93ef-72ad5fc0d77c', '### Réforme des institutions : le débat sur la décentralisation relancé

Le débat sur la décentralisation refait surface dans l''hexagone, alors que le gouvernement vient de déposer un projet de loi visant à transférer de nouvelles compétences aux régions. Cette réforme, dont l''ambition affichée est de rapprocher les centres de décision des citoyens, suscite toutefois des réactions contrastées au sein de la classe politique.

Si les partisans de la mesure estiment qu''elle permettrait une gestion plus efficace des politiques publiques, notamment dans les domaines de l''éducation et des transports, ses détracteurs craignent qu''elle n''accentue les inégalités territoriales. « Il serait illusoire de croire que toutes les régions disposent des mêmes capacités financières pour assumer ces nouvelles responsabilités », a déclaré un élu de l''opposition, soulignant qu''il faudrait que l''État garantisse une péréquation équitable avant d''envisager un quelconque transfert de compétences.

Le texte prévoit également la création d''un fonds de solidarité destiné à compenser les disparités économiques entre les territoires. Les débats parlementaires devraient s''étendre sur plusieurs mois, et de nombreux amendements sont attendus de la part des sénateurs qui souhaitent que le rôle des collectivités locales soit renforcé dans la mise en œuvre de cette politique ambitieuse. Les citoyens, quant à eux, attendent des résultats concrets : une enquête récente révèle que 68% des Français se disent favorables à une décentralisation accrue, pourvu qu''elle s''accompagne de moyens financiers à la hauteur des enjeux.

Question : Quel est le sujet principal de cet article ?', NULL, '["Un projet de loi sur la décentralisation et ses implications", "Les élections municipales à venir en France", "La réforme du système de santé français", "Les relations entre la France et l''Union européenne"]', 'Un projet de loi sur la décentralisation et ses implications', 1, 4, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('45486faa-1463-47db-98d8-ed04c9013580', 'f61d727f-858f-42bf-93ef-72ad5fc0d77c', '### Les nouvelles solidarités face à la fragmentation du lien social

La société française contemporaine est traversée par des tensions qui interrogent la cohésion nationale. Entre individualisme croissant et fragmentation sociale, de nouvelles formes de solidarité émergent pourtant, témoignant d''une capacité de résilience collective. Les associations et les initiatives citoyennes se multiplient, notamment dans les domaines de l''aide alimentaire, du soutien scolaire et de l''accompagnement des personnes isolées. Il est remarquable que l''engagement citoyen se renouvelle malgré un contexte de défiance envers les institutions.

« On observe une véritable renaissance de l''engagement citoyen, particulièrement chez les jeunes générations », explique une sociologue spécialiste des mouvements associatifs. Selon une enquête récente, 62% des 18-35 ans déclarent avoir participé à au moins une action bénévole au cours des douze derniers mois, un chiffre en hausse constante depuis cinq ans. Il serait intéressant que les pouvoirs publics s''appuient davantage sur cet élan pour renforcer les politiques de cohésion sociale.

Les plateformes numériques jouent un rôle catalyseur dans cette recomposition du lien social, en facilitant la mise en relation des volontaires et des personnes dans le besoin. Cependant, des voix s''élèvent pour mettre en garde contre une « ubérisation » de la solidarité qui affaiblirait les services publics. Le débat sur le rôle de l''État et de la société civile dans la protection sociale reste plus que jamais d''actualité. Une enquête d''opinion révèle que 76% des Français estiment que la solidarité est une valeur fondamentale qui devrait être davantage encouragée par les politiques publiques.

Question : Quelle est l''attitude des jeunes générations vis-à-vis de l''engagement citoyen ?', NULL, '["Elles sont de plus en plus engagées, avec une hausse constante du bénévolat", "Elles se désintéressent complètement de l''engagement associatif", "Elles préfèrent les engagements politiques traditionnels", "Elles sont moins engagées que les générations précédentes"]', 'Elles sont de plus en plus engagées, avec une hausse constante du bénévolat', 1, 5, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('dc6fa3e7-b268-478b-ab2d-373309309932', '907602a7-d59c-4ad7-bebd-96d3e95bcf7c', '### Conditions générales : Assurance voyage

L''assureur garantit le remboursement des frais médicaux engagés à l''étranger suite à un accident ou une maladie imprévisible. La prise en charge est plafonnée à 50 000€ par assuré et par sinistre, après application d''une franchise de 30€. Sont exclus de la garantie les traitements liés à des pathologies préexistantes non stabilisées ainsi que les soins de confort. En cas d''hospitalisation, l''assuré doit impérativement contacter le plateau d''assistance dans les 24 heures pour obtenir un accord préalable de prise en charge directe, sous peine de voir sa demande de remboursement rejetée.

Question : Que doit faire l''assuré en cas d''hospitalisation ?', NULL, '["Rien, c''est automatique", "Payer la totalité d''abord", "Contacter l''assistance sous 24h", "Envoyer une lettre recommandée un mois après"]', 'Contacter l''assistance sous 24h', 1, 6, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('73eef5ac-8d2e-42f3-879c-3cb0b09f035e', 'f61d727f-858f-42bf-93ef-72ad5fc0d77c', '### Politique d''immigration au Canada : le français comme vecteur d''intégration

Le Canada renforce sa politique d''immigration francophone en dehors du Québec, avec l''objectif ambitieux d''atteindre 12% d''immigrants francophones d''ici 2028 dans les provinces et territoires anglophones. Cette stratégie, qui s''inscrit dans le cadre de la Loi sur les langues officielles, vise à contrer le déclin du poids démographique des communautés francophones hors Québec. Il est essentiel que les nouveaux arrivants puissent s''intégrer pleinement dans la société canadienne.

« La maîtrise du français constitue un atout indéniable pour les candidats à l''immigration, leur permettant d''accumuler des points supplémentaires dans le système Entrée express », rappelle une conseillère en immigration basée à Toronto. Les données officielles indiquent que les candidats francophones obtiennent en moyenne des scores plus élevés et que leur dossier est traité plus rapidement. Le gouvernement fédéral souhaite que les provinces collaborent davantage à la mise en œuvre de cette stratégie linguistique.

Les nouveaux arrivants francophones bénéficient par ailleurs de programmes d''accompagnement spécifiques, notamment des services d''établissement et des cours de perfectionnement linguistique. Cependant, des défis persistent, particulièrement en ce qui concerne l''accès à l''emploi dans leur domaine de compétence. Des associations militent pour que les diplômes étrangers soient mieux reconnus et que l''accompagnement vers l''intégration professionnelle soit renforcé. Selon une étude récente, 71% des immigrants francophones trouvent un emploi dans leur domaine dans les deux ans suivant leur arrivée, un chiffre encourageant mais qui pourrait encore être amélioré.

Question : Pourquoi l''auteur mentionne-t-il le chiffre de 71% d''emploi dans le domaine ?', NULL, '["Pour montrer un résultat encourageant tout en suggérant des marges d''amélioration", "Pour prouver que l''intégration professionnelle est un échec", "Pour démontrer que le système actuel est parfait", "Pour critiquer les politiques d''immigration actuelles"]', 'Pour montrer un résultat encourageant tout en suggérant des marges d''amélioration', 1, 7, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('23334880-83cd-435d-91ba-308ef1edb833', 'f61d727f-858f-42bf-93ef-72ad5fc0d77c', '### La culture française à l''ère du numérique : entre tradition et innovation

Le paysage culturel français connaît une mutation profonde sous l''effet des nouvelles technologies. Si les salles de cinéma et les théâtres ont vu leur fréquentation diminuer de 15% depuis la crise sanitaire, les plateformes numériques enregistrent une croissance exponentielle de leur audience, notamment chez les jeunes générations. Il serait pourtant regrettable que la culture en ligne se substitue entièrement à l''expérience physique du spectacle vivant.

Le ministère de la Culture a récemment dévoilé un plan de soutien à la création artistique doté de 300 millions d''euros, visant à accompagner les acteurs culturels dans leur transition numérique. « Il est impératif que notre patrimoine culturel demeure accessible au plus grand nombre, tout en s''adaptant aux nouveaux usages », a déclaré la ministre lors d''une conférence de presse. Ce plan prévoit notamment la numérisation de 500 000 œuvres issues des collections nationales, dont une large part n''avait jamais été accessible au public.

Les festivals, véritables institutions de la vie culturelle française, réinventent également leur modèle. Le Festival d''Avignon, plus grand rendez-vous de théâtre contemporain d''Europe, propose désormais une programmation hybride alliant représentations physiques et diffusions en ligne. Cette stratégie permet de toucher un public international tout en préservant l''essence même de l''expérience théâtrale. Selon une enquête, 58% des spectateurs estiment que le numérique enrichit leur expérience culturelle sans la remplacer.

Question : De combien la fréquentation des salles de cinéma et théâtres a-t-elle diminué ?', NULL, '["5%", "10%", "15%", "20%"]', '15%', 1, 8, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('d7d69ce6-119a-4583-b03f-7d59c08c2165', 'f61d727f-858f-42bf-93ef-72ad5fc0d77c', '### Politique d''immigration au Canada : le français comme vecteur d''intégration

Le Canada renforce sa politique d''immigration francophone en dehors du Québec, avec l''objectif ambitieux d''atteindre 12% d''immigrants francophones d''ici 2028 dans les provinces et territoires anglophones. Cette stratégie, qui s''inscrit dans le cadre de la Loi sur les langues officielles, vise à contrer le déclin du poids démographique des communautés francophones hors Québec. Il est essentiel que les nouveaux arrivants puissent s''intégrer pleinement dans la société canadienne.

« La maîtrise du français constitue un atout indéniable pour les candidats à l''immigration, leur permettant d''accumuler des points supplémentaires dans le système Entrée express », rappelle une conseillère en immigration basée à Toronto. Les données officielles indiquent que les candidats francophones obtiennent en moyenne des scores plus élevés et que leur dossier est traité plus rapidement. Le gouvernement fédéral souhaite que les provinces collaborent davantage à la mise en œuvre de cette stratégie linguistique.

Les nouveaux arrivants francophones bénéficient par ailleurs de programmes d''accompagnement spécifiques, notamment des services d''établissement et des cours de perfectionnement linguistique. Cependant, des défis persistent, particulièrement en ce qui concerne l''accès à l''emploi dans leur domaine de compétence. Des associations militent pour que les diplômes étrangers soient mieux reconnus et que l''accompagnement vers l''intégration professionnelle soit renforcé. Selon une étude récente, 71% des immigrants francophones trouvent un emploi dans leur domaine dans les deux ans suivant leur arrivée, un chiffre encourageant mais qui pourrait encore être amélioré.

Question : Quel est l''objectif chiffré concernant les immigrants francophones d''ici 2028 ?', NULL, '["8%", "10%", "12%", "15%"]', '12%', 1, 9, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('e1121b04-c0a3-4cb6-b597-7ca91f47dd37', '907602a7-d59c-4ad7-bebd-96d3e95bcf7c', '### Vente de véhicule d''occasion

Berline hybride de 2021, 45 000 km, entretien exclusif en concession. Véhicule non-fumeur, toujours stationné en garage fermé. Équipements premium : toit ouvrant panoramique, aide au stationnement 360°, régulateur de vitesse adaptatif. Garantie constructeur encore valable 12 mois. Prix : 22 500 € à débattre dans la limite du raisonnable. Premier contact par courriel uniquement. Agences s''abstenir.

Question : Comment l''acheteur doit-il contacter le vendeur ?', NULL, '["Par téléphone", "Par SMS", "Par courriel", "En se rendant sur place"]', 'Par courriel', 1, 10, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('dae3bef2-177c-4b06-a64d-834142fddcf0', 'f61d727f-858f-42bf-93ef-72ad5fc0d77c', '### La biodiversité en péril : l''urgence d''agir face à l''effondrement des écosystèmes

L''érosion de la biodiversité s''accélère à un rythme préoccupant, selon le dernier rapport du Groupe d''experts intergouvernemental sur l''évolution du climat (GIEC). Près d''un million d''espèces animales et végétales seraient menacées d''extinction à court terme, principalement en raison des activités humaines et du dérèglement climatique. Il est impératif que des mesures drastiques soient adoptées sans délai pour inverser cette tendance.

Face à ce constat alarmant, de nombreuses initiatives voient le jour tant au niveau local qu''international. La France a notamment annoncé le lancement d''un programme de restauration écologique portant sur 50 000 hectares de zones humides d''ici 2030. Ces écosystèmes, qui jouent un rôle crucial dans la régulation du climat et la filtration de l''eau, ont vu leur superficie diminuer de 67% au cours du siècle dernier. Il serait regrettable que les efforts ne soient pas à la hauteur de l''urgence.

Les scientifiques insistent sur la nécessité d''adopter une approche systémique. « Il ne suffit pas que nous protégions quelques espèces emblématiques ; il faut que nous préservions l''intégralité des écosystèmes dont dépend notre propre survie », explique une chercheuse du Muséum national d''histoire naturelle. Les décisions politiques prises dans les prochaines années seront déterminantes pour inverser cette tendance. Selon un sondage, 73% des citoyens européens considèrent que la protection de l''environnement devrait être une priorité absolue, ce qui témoigne d''une sensibilisation croissante de l''opinion publique.

Question : Quel est l''objectif du programme de restauration écologique annoncé par la France ?', NULL, '["Restaurer 50 000 hectares de zones humides d''ici 2030", "Planter un million d''arbres d''ici 2025", "Réduire les émissions de CO2 de 40% d''ici 2030", "Créer 100 nouvelles réserves naturelles"]', 'Restaurer 50 000 hectares de zones humides d''ici 2030', 1, 11, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('1ab055cb-ef07-4339-8ad0-d115883753a8', '907602a7-d59c-4ad7-bebd-96d3e95bcf7c', '### Annonce immobilière : Loft industriel

À louer, magnifique loft de style industriel situé au cœur du quartier de la création. Cet espace de 120m² offre de hauts plafonds, une luminosité exceptionnelle grâce à de grandes verrières et un parquet d''origine restauré. Le bien comprend une cuisine ouverte entièrement équipée, une vaste pièce de vie, deux chambres et une salle de bain avec douche à l''italienne. Chauffage collectif urbain inclus dans les charges. Idéal pour une activité professionnelle libérale ou un usage résidentiel. Disponible immédiatement. Une garantie bancaire de deux mois de loyer hors charges est exigée à la signature du bail.

Question : Quelle est la particularité architecturale du loft ?', NULL, '["Il est au sous-sol", "Il a de hauts plafonds et des verrières", "Il est construit en bois uniquement", "Il n''a pas de fenêtres"]', 'Il a de hauts plafonds et des verrières', 1, 12, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('391fafc2-d9d2-4c2c-8c36-b4f7a56a057a', 'f61d727f-858f-42bf-93ef-72ad5fc0d77c', '### L''école face aux défis du XXIe siècle : réformer pour mieux former

Le système éducatif français est engagé dans une vaste réforme visant à adapter l''enseignement aux enjeux contemporains. Au cœur de cette transformation, l''accent est mis sur l''apprentissage des langues étrangères, le développement des compétences numériques et l''éducation au développement durable. Il est indispensable que les élèves acquièrent les compétences qui leur permettront de s''épanouir dans un monde en constante évolution.

« Il convient que nos élèves soient préparés à évoluer dans un monde où les frontières professionnelles et géographiques sont de plus en plus poreuses », souligne un rapport de l''OCDE. Les résultats de la France aux évaluations internationales PISA, bien qu''en légère amélioration, demeurent inférieurs à la moyenne des pays comparables. Cette situation a motivé l''introduction de nouvelles méthodes pédagogiques, notamment l''enseignement par projet et l''évaluation par compétences. Il faudrait que les enseignants soient mieux formés à ces nouvelles approches pour qu''elles portent leurs fruits.

La réforme prévoit également la création de « cités éducatives » dans les quartiers prioritaires, visant à renforcer la coopération entre l''école, les familles et les acteurs locaux. Un budget supplémentaire de 800 millions d''euros a été débloqué pour réduire les effectifs dans les classes et améliorer l''équité territoriale. Le taux de décrochage scolaire, qui touche encore près de 8% des jeunes Français, est jugé préoccupant par les syndicats enseignants. Selon une enquête, 64% des parents estiment que l''école devrait accorder une place plus importante à l''éducation aux médias et à l''information.

Question : Que peut-on déduire des résultats de la France aux évaluations PISA ?', NULL, '["Ils sont en progrès mais insuffisants par rapport aux pays comparables", "La France est classée première mondialement", "Les résultats sont en baisse constante depuis dix ans", "La France a refusé de participer aux évaluations"]', 'Ils sont en progrès mais insuffisants par rapport aux pays comparables', 1, 13, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('4edd5156-a999-4304-87a1-5bf3aa32b049', 'f61d727f-858f-42bf-93ef-72ad5fc0d77c', '### La culture française à l''ère du numérique : entre tradition et innovation

Le paysage culturel français connaît une mutation profonde sous l''effet des nouvelles technologies. Si les salles de cinéma et les théâtres ont vu leur fréquentation diminuer de 15% depuis la crise sanitaire, les plateformes numériques enregistrent une croissance exponentielle de leur audience, notamment chez les jeunes générations. Il serait pourtant regrettable que la culture en ligne se substitue entièrement à l''expérience physique du spectacle vivant.

Le ministère de la Culture a récemment dévoilé un plan de soutien à la création artistique doté de 300 millions d''euros, visant à accompagner les acteurs culturels dans leur transition numérique. « Il est impératif que notre patrimoine culturel demeure accessible au plus grand nombre, tout en s''adaptant aux nouveaux usages », a déclaré la ministre lors d''une conférence de presse. Ce plan prévoit notamment la numérisation de 500 000 œuvres issues des collections nationales, dont une large part n''avait jamais été accessible au public.

Les festivals, véritables institutions de la vie culturelle française, réinventent également leur modèle. Le Festival d''Avignon, plus grand rendez-vous de théâtre contemporain d''Europe, propose désormais une programmation hybride alliant représentations physiques et diffusions en ligne. Cette stratégie permet de toucher un public international tout en préservant l''essence même de l''expérience théâtrale. Selon une enquête, 58% des spectateurs estiment que le numérique enrichit leur expérience culturelle sans la remplacer.

Question : Quel est l''objectif de l''article en mentionnant le sondage sur les spectateurs ?', NULL, '["Montrer que le numérique est perçu comme un enrichissement et non un remplacement", "Démontrer que les spectateurs préfèrent le numérique au spectacle vivant", "Prouver que la culture traditionnelle est en voie de disparition", "Illustrer le désintérêt des jeunes pour la culture"]', 'Montrer que le numérique est perçu comme un enrichissement et non un remplacement', 1, 14, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('9171c9f0-f4f9-4a6b-b3d8-2d4e42420241', 'f61d727f-858f-42bf-93ef-72ad5fc0d77c', '### La culture française à l''ère du numérique : entre tradition et innovation

Le paysage culturel français connaît une mutation profonde sous l''effet des nouvelles technologies. Si les salles de cinéma et les théâtres ont vu leur fréquentation diminuer de 15% depuis la crise sanitaire, les plateformes numériques enregistrent une croissance exponentielle de leur audience, notamment chez les jeunes générations. Il serait pourtant regrettable que la culture en ligne se substitue entièrement à l''expérience physique du spectacle vivant.

Le ministère de la Culture a récemment dévoilé un plan de soutien à la création artistique doté de 300 millions d''euros, visant à accompagner les acteurs culturels dans leur transition numérique. « Il est impératif que notre patrimoine culturel demeure accessible au plus grand nombre, tout en s''adaptant aux nouveaux usages », a déclaré la ministre lors d''une conférence de presse. Ce plan prévoit notamment la numérisation de 500 000 œuvres issues des collections nationales, dont une large part n''avait jamais été accessible au public.

Les festivals, véritables institutions de la vie culturelle française, réinventent également leur modèle. Le Festival d''Avignon, plus grand rendez-vous de théâtre contemporain d''Europe, propose désormais une programmation hybride alliant représentations physiques et diffusions en ligne. Cette stratégie permet de toucher un public international tout en préservant l''essence même de l''expérience théâtrale. Selon une enquête, 58% des spectateurs estiment que le numérique enrichit leur expérience culturelle sans la remplacer.

Question : Que signifie « programmation hybride » dans le contexte du Festival d''Avignon ?', NULL, '["Un mélange de représentations physiques et de diffusions en ligne", "Une sélection d''œuvres mélangeant théâtre et danse", "Un programme organisé en collaboration avec plusieurs pays", "Un calendrier alternant spectacles gratuits et payants"]', 'Un mélange de représentations physiques et de diffusions en ligne', 1, 15, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('ce8dd73f-d91f-42d3-b4eb-e1893b2f2381', 'f61d727f-858f-42bf-93ef-72ad5fc0d77c', '### Système de santé : les défis de la médecine de demain face au vieillissement

Le système de santé français, longtemps considéré comme l''un des meilleurs au monde, traverse une période de turbulences sans précédent. La pénurie de personnel soignant, couplée au vieillissement de la population, exerce une pression croissante sur les hôpitaux publics. Selon un rapport du Haut Conseil de la santé publique, la France compterait 3,5 millions de personnes âgées dépendantes en 2030, soit une augmentation de 40% par rapport à 2020. Il est urgent que des mesures structurelles soient adoptées pour faire face à cette situation.

Face à cette situation, les pouvoirs publics misent sur la télémédecine et les innovations technologiques. « Les consultations à distance ont connu une augmentation de 500% depuis 2020, et cette tendance devrait se poursuivre », explique un chercheur en santé numérique. Le gouvernement a alloué une enveloppe de 500 millions d''euros pour moderniser les infrastructures hospitalières et développer les soins à domicile. Il faudrait que ces investissements soient pérennisés pour garantir leur efficacité à long terme.

Les professionnels de santé réclament quant à eux une revalorisation salariale et des conditions de travail plus attractives. « Il serait illusoire de vouloir réformer le système sans investir dans les ressources humaines », prévient un syndicat médical. La question du financement à long terme de la protection sociale demeure au cœur des débats politiques, d''autant que le vieillissement démographique devrait accroître les dépenses de santé de 1,5% par an en moyenne jusqu''en 2040, selon les projections de la Commission des comptes de la sécurité sociale.

Question : Combien de personnes âgées dépendantes la France comptera-t-elle en 2030 ?', NULL, '["2,5 millions", "3 millions", "3,5 millions", "4 millions"]', '3,5 millions', 1, 16, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('8be93bf8-8726-44a4-8ba5-e58be50239fd', 'f61d727f-858f-42bf-93ef-72ad5fc0d77c', '### Réforme des institutions : le débat sur la décentralisation relancé

Le débat sur la décentralisation refait surface dans l''hexagone, alors que le gouvernement vient de déposer un projet de loi visant à transférer de nouvelles compétences aux régions. Cette réforme, dont l''ambition affichée est de rapprocher les centres de décision des citoyens, suscite toutefois des réactions contrastées au sein de la classe politique.

Si les partisans de la mesure estiment qu''elle permettrait une gestion plus efficace des politiques publiques, notamment dans les domaines de l''éducation et des transports, ses détracteurs craignent qu''elle n''accentue les inégalités territoriales. « Il serait illusoire de croire que toutes les régions disposent des mêmes capacités financières pour assumer ces nouvelles responsabilités », a déclaré un élu de l''opposition, soulignant qu''il faudrait que l''État garantisse une péréquation équitable avant d''envisager un quelconque transfert de compétences.

Le texte prévoit également la création d''un fonds de solidarité destiné à compenser les disparités économiques entre les territoires. Les débats parlementaires devraient s''étendre sur plusieurs mois, et de nombreux amendements sont attendus de la part des sénateurs qui souhaitent que le rôle des collectivités locales soit renforcé dans la mise en œuvre de cette politique ambitieuse. Les citoyens, quant à eux, attendent des résultats concrets : une enquête récente révèle que 68% des Français se disent favorables à une décentralisation accrue, pourvu qu''elle s''accompagne de moyens financiers à la hauteur des enjeux.

Question : Que signifie le mot « péréquation » dans le contexte de cet article ?', NULL, '["Un mécanisme de redistribution visant à réduire les inégalités", "Une augmentation des impôts locaux", "Une procédure de vote parlementaire", "Un système de nomination des fonctionnaires régionaux"]', 'Un mécanisme de redistribution visant à réduire les inégalités', 1, 17, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('1364a4f1-843f-4c51-a963-207072a0d247', 'f61d727f-858f-42bf-93ef-72ad5fc0d77c', '### La biodiversité en péril : l''urgence d''agir face à l''effondrement des écosystèmes

L''érosion de la biodiversité s''accélère à un rythme préoccupant, selon le dernier rapport du Groupe d''experts intergouvernemental sur l''évolution du climat (GIEC). Près d''un million d''espèces animales et végétales seraient menacées d''extinction à court terme, principalement en raison des activités humaines et du dérèglement climatique. Il est impératif que des mesures drastiques soient adoptées sans délai pour inverser cette tendance.

Face à ce constat alarmant, de nombreuses initiatives voient le jour tant au niveau local qu''international. La France a notamment annoncé le lancement d''un programme de restauration écologique portant sur 50 000 hectares de zones humides d''ici 2030. Ces écosystèmes, qui jouent un rôle crucial dans la régulation du climat et la filtration de l''eau, ont vu leur superficie diminuer de 67% au cours du siècle dernier. Il serait regrettable que les efforts ne soient pas à la hauteur de l''urgence.

Les scientifiques insistent sur la nécessité d''adopter une approche systémique. « Il ne suffit pas que nous protégions quelques espèces emblématiques ; il faut que nous préservions l''intégralité des écosystèmes dont dépend notre propre survie », explique une chercheuse du Muséum national d''histoire naturelle. Les décisions politiques prises dans les prochaines années seront déterminantes pour inverser cette tendance. Selon un sondage, 73% des citoyens européens considèrent que la protection de l''environnement devrait être une priorité absolue, ce qui témoigne d''une sensibilisation croissante de l''opinion publique.

Question : Que peut-on déduire de l''opinion des citoyens européens sur l''environnement ?', NULL, '["Une majorité significative considère l''environnement comme une priorité", "Les citoyens européens sont indifférents aux questions environnementales", "Seule une minorité soutient les politiques environnementales", "Les jeunes sont les seuls à se préoccuper de l''environnement"]', 'Une majorité significative considère l''environnement comme une priorité', 1, 18, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('042bc0cd-9ee1-4d4d-8a65-d524f3d97a89', 'f61d727f-858f-42bf-93ef-72ad5fc0d77c', '### L''école face aux défis du XXIe siècle : réformer pour mieux former

Le système éducatif français est engagé dans une vaste réforme visant à adapter l''enseignement aux enjeux contemporains. Au cœur de cette transformation, l''accent est mis sur l''apprentissage des langues étrangères, le développement des compétences numériques et l''éducation au développement durable. Il est indispensable que les élèves acquièrent les compétences qui leur permettront de s''épanouir dans un monde en constante évolution.

« Il convient que nos élèves soient préparés à évoluer dans un monde où les frontières professionnelles et géographiques sont de plus en plus poreuses », souligne un rapport de l''OCDE. Les résultats de la France aux évaluations internationales PISA, bien qu''en légère amélioration, demeurent inférieurs à la moyenne des pays comparables. Cette situation a motivé l''introduction de nouvelles méthodes pédagogiques, notamment l''enseignement par projet et l''évaluation par compétences. Il faudrait que les enseignants soient mieux formés à ces nouvelles approches pour qu''elles portent leurs fruits.

La réforme prévoit également la création de « cités éducatives » dans les quartiers prioritaires, visant à renforcer la coopération entre l''école, les familles et les acteurs locaux. Un budget supplémentaire de 800 millions d''euros a été débloqué pour réduire les effectifs dans les classes et améliorer l''équité territoriale. Le taux de décrochage scolaire, qui touche encore près de 8% des jeunes Français, est jugé préoccupant par les syndicats enseignants. Selon une enquête, 64% des parents estiment que l''école devrait accorder une place plus importante à l''éducation aux médias et à l''information.

Question : Pourquoi l''auteur mentionne-t-il l''enquête sur les parents concernant l''éducation aux médias ?', NULL, '["Pour montrer une demande sociale en faveur de nouvelles compétences éducatives", "Pour démontrer que les parents sont satisfaits du système actuel", "Pour prouver que l''éducation aux médias est déjà bien enseignée", "Pour critiquer l''absence totale de formation des enseignants"]', 'Pour montrer une demande sociale en faveur de nouvelles compétences éducatives', 1, 19, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('825ecb12-31a6-4c84-a4d7-45142bfd6cdf', '907602a7-d59c-4ad7-bebd-96d3e95bcf7c', '### Contrat de travail : Clause de non-concurrence

L''article 12 du présent contrat stipule qu''en cas de rupture de la relation de travail, quel qu''en soit le motif, le salarié s''interdit d''exercer une activité concurrente à celle de l''employeur. Cette interdiction est limitée à une durée de 12 mois et s''applique sur le territoire de la province de l''Ontario. En contrepartie de cette obligation, l''employeur versera au salarié, pendant toute la durée de l''interdiction, une indemnité compensatrice mensuelle égale à 33% de la moyenne de son salaire brut des trois derniers mois. L''employeur se réserve le droit de renoncer à cette clause, à condition d''en informer le salarié par écrit dans les 15 jours suivant la notification de la rupture.

Question : Quelle est la contrepartie financière pour le salarié ?', NULL, '["Rien, c''est obligatoire", "33% de son ancien salaire brut", "Une prime unique à la fin", "100% de son salaire"]', '33% de son ancien salaire brut', 1, 20, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('4834ef5d-ec99-4847-8461-3f9c8dd25395', 'f61d727f-858f-42bf-93ef-72ad5fc0d77c', '### Système de santé : les défis de la médecine de demain face au vieillissement

Le système de santé français, longtemps considéré comme l''un des meilleurs au monde, traverse une période de turbulences sans précédent. La pénurie de personnel soignant, couplée au vieillissement de la population, exerce une pression croissante sur les hôpitaux publics. Selon un rapport du Haut Conseil de la santé publique, la France compterait 3,5 millions de personnes âgées dépendantes en 2030, soit une augmentation de 40% par rapport à 2020. Il est urgent que des mesures structurelles soient adoptées pour faire face à cette situation.

Face à cette situation, les pouvoirs publics misent sur la télémédecine et les innovations technologiques. « Les consultations à distance ont connu une augmentation de 500% depuis 2020, et cette tendance devrait se poursuivre », explique un chercheur en santé numérique. Le gouvernement a alloué une enveloppe de 500 millions d''euros pour moderniser les infrastructures hospitalières et développer les soins à domicile. Il faudrait que ces investissements soient pérennisés pour garantir leur efficacité à long terme.

Les professionnels de santé réclament quant à eux une revalorisation salariale et des conditions de travail plus attractives. « Il serait illusoire de vouloir réformer le système sans investir dans les ressources humaines », prévient un syndicat médical. La question du financement à long terme de la protection sociale demeure au cœur des débats politiques, d''autant que le vieillissement démographique devrait accroître les dépenses de santé de 1,5% par an en moyenne jusqu''en 2040, selon les projections de la Commission des comptes de la sécurité sociale.

Question : Quelle est l''attitude des professionnels de santé face aux réformes ?', NULL, '["Ils estiment que les réformes doivent s''accompagner d''investissements humains", "Ils refusent toute forme de modernisation du système", "Ils sont satisfaits des conditions de travail actuelles", "Ils préfèrent que les réformes soient reportées"]', 'Ils estiment que les réformes doivent s''accompagner d''investissements humains', 1, 21, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('dc4464f3-36a3-412c-a092-ea840578118f', 'f61d727f-858f-42bf-93ef-72ad5fc0d77c', '### La culture française à l''ère du numérique : entre tradition et innovation

Le paysage culturel français connaît une mutation profonde sous l''effet des nouvelles technologies. Si les salles de cinéma et les théâtres ont vu leur fréquentation diminuer de 15% depuis la crise sanitaire, les plateformes numériques enregistrent une croissance exponentielle de leur audience, notamment chez les jeunes générations. Il serait pourtant regrettable que la culture en ligne se substitue entièrement à l''expérience physique du spectacle vivant.

Le ministère de la Culture a récemment dévoilé un plan de soutien à la création artistique doté de 300 millions d''euros, visant à accompagner les acteurs culturels dans leur transition numérique. « Il est impératif que notre patrimoine culturel demeure accessible au plus grand nombre, tout en s''adaptant aux nouveaux usages », a déclaré la ministre lors d''une conférence de presse. Ce plan prévoit notamment la numérisation de 500 000 œuvres issues des collections nationales, dont une large part n''avait jamais été accessible au public.

Les festivals, véritables institutions de la vie culturelle française, réinventent également leur modèle. Le Festival d''Avignon, plus grand rendez-vous de théâtre contemporain d''Europe, propose désormais une programmation hybride alliant représentations physiques et diffusions en ligne. Cette stratégie permet de toucher un public international tout en préservant l''essence même de l''expérience théâtrale. Selon une enquête, 58% des spectateurs estiment que le numérique enrichit leur expérience culturelle sans la remplacer.

Question : Quel est le sujet principal de cet article ?', NULL, '["La transformation du secteur culturel à l''ère numérique", "La fermeture des salles de cinéma en France", "L''histoire du Festival d''Avignon", "Le budget du ministère de la Culture"]', 'La transformation du secteur culturel à l''ère numérique', 1, 22, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('e33db0e3-333c-44e4-a681-344beceb4964', 'f61d727f-858f-42bf-93ef-72ad5fc0d77c', '### Géopolitique mondiale : l''émergence d''un nouvel ordre international

Les relations internationales connaissent actuellement des bouleversements majeurs, marqués par l''affirmation de nouvelles puissances et la remise en cause des équilibres établis depuis la fin de la guerre froide. L''essor économique de la Chine, le retour de la Russie sur la scène diplomatique et l''émergence du G20 comme forum de concertation privilégié redessinent la carte du pouvoir mondial. Il est probable que cette recomposition géopolitique s''accélère dans les années à venir.

« Nous assistons à une transition historique vers un monde multipolaire, où les alliances traditionnelles sont réévaluées », analyse une chercheuse en relations internationales de Sciences Po. Les organisations internationales, notamment l''ONU et l''OMC, peinent à s''adapter à cette nouvelle configuration, ce qui suscite des interrogations sur leur capacité à réguler les conflits et les échanges mondiaux. Il faudrait que ces institutions soient réformées en profondeur pour rester pertinentes.

La France, forte de son réseau diplomatique et de sa présence au Conseil de sécurité, cherche à maintenir son influence tout en nouant de nouveaux partenariats stratégiques. Le président a récemment plaidé pour une « autonomie stratégique européenne » lors d''un sommet à Bruxelles, appelant les États membres à renforcer leur coopération en matière de défense et de politique étrangère. Selon un sondage réalisé dans six pays européens, 58% des citoyens se déclarent favorables à une politique étrangère commune, bien que les divergences entre États membres restent importantes.

Question : Que signifie « autonomie stratégique européenne » dans le contexte ?', NULL, '["La capacité de l''Europe à agir indépendamment sur la scène internationale", "L''indépendance énergétique totale de l''Europe", "La fermeture des frontières européennes", "Le retrait de l''Europe de l''OTAN"]', 'La capacité de l''Europe à agir indépendamment sur la scène internationale', 1, 23, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('86fa452e-743f-492d-835a-780752e6cd5e', 'f61d727f-858f-42bf-93ef-72ad5fc0d77c', '### L''intelligence artificielle transforme le marché du travail : quelles perspectives ?

L''intelligence artificielle générative bouleverse les codes établis du monde professionnel, suscitant à la fois enthousiasme et inquiétude. Selon une étude prospective du Ministère du Travail, près de 30% des métiers actuels pourraient être profondément transformés par ces technologies d''ici 2030, tandis que de nouvelles professions émergeraient simultanément. Il est essentiel que les travailleurs anticipent ces mutations pour ne pas être pris au dépourvu.

Les secteurs les plus impactés seraient ceux de la traduction, du journalisme, de la programmation informatique et des services juridiques. « L''IA ne remplacera pas les humains, mais il est probable que les professionnels qui sauront exploiter ces outils remplaceront ceux qui les ignorent », affirme un expert en transformation numérique interrogé par nos confrères du Monde. Cette citation illustre bien le paradoxe auquel sont confrontés les travailleurs : il faudrait qu''ils se forment aux nouvelles technologies tout en conservant leur expertise métier.

Parallèlement, le gouvernement a annoncé un plan d''investissement de deux milliards d''euros pour former les travailleurs aux compétences numériques de demain. Ce programme ambitieux comprend notamment la création de cinquante campus dédiés à l''intelligence artificielle sur l''ensemble du territoire. Les syndicats restent toutefois vigilants quant aux conditions de mise en œuvre de cette transition technologique, craignant qu''elle ne se traduise par une précarisation accrue de certains emplois. Une enquête récente indique que 62% des salariés français se disent préoccupés par l''impact de l''IA sur leur travail.

Question : Que signifie l''expression « précarisation accrue » dans le contexte ?', NULL, '["Une augmentation de l''instabilité et de la vulnérabilité professionnelle", "Une amélioration des conditions de travail", "Une réduction du temps de travail hebdomadaire", "Une augmentation générale des salaires"]', 'Une augmentation de l''instabilité et de la vulnérabilité professionnelle', 1, 24, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('d24765bc-3798-4f2c-9422-cec8cb2403b9', '907602a7-d59c-4ad7-bebd-96d3e95bcf7c', '### Annonce immobilière : Loft industriel

À louer, magnifique loft de style industriel situé au cœur du quartier de la création. Cet espace de 120m² offre de hauts plafonds, une luminosité exceptionnelle grâce à de grandes verrières et un parquet d''origine restauré. Le bien comprend une cuisine ouverte entièrement équipée, une vaste pièce de vie, deux chambres et une salle de bain avec douche à l''italienne. Chauffage collectif urbain inclus dans les charges. Idéal pour une activité professionnelle libérale ou un usage résidentiel. Disponible immédiatement. Une garantie bancaire de deux mois de loyer hors charges est exigée à la signature du bail.

Question : Quelle condition est nécessaire pour louer ce bien ?', NULL, '["Avoir un chien", "Fournir une garantie bancaire de deux mois", "Travailler de nuit", "Être étudiant"]', 'Fournir une garantie bancaire de deux mois', 1, 25, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('2effbe9f-4904-4e3e-a79a-df2c7e19b3e2', 'f61d727f-858f-42bf-93ef-72ad5fc0d77c', '### Les nouvelles solidarités face à la fragmentation du lien social

La société française contemporaine est traversée par des tensions qui interrogent la cohésion nationale. Entre individualisme croissant et fragmentation sociale, de nouvelles formes de solidarité émergent pourtant, témoignant d''une capacité de résilience collective. Les associations et les initiatives citoyennes se multiplient, notamment dans les domaines de l''aide alimentaire, du soutien scolaire et de l''accompagnement des personnes isolées. Il est remarquable que l''engagement citoyen se renouvelle malgré un contexte de défiance envers les institutions.

« On observe une véritable renaissance de l''engagement citoyen, particulièrement chez les jeunes générations », explique une sociologue spécialiste des mouvements associatifs. Selon une enquête récente, 62% des 18-35 ans déclarent avoir participé à au moins une action bénévole au cours des douze derniers mois, un chiffre en hausse constante depuis cinq ans. Il serait intéressant que les pouvoirs publics s''appuient davantage sur cet élan pour renforcer les politiques de cohésion sociale.

Les plateformes numériques jouent un rôle catalyseur dans cette recomposition du lien social, en facilitant la mise en relation des volontaires et des personnes dans le besoin. Cependant, des voix s''élèvent pour mettre en garde contre une « ubérisation » de la solidarité qui affaiblirait les services publics. Le débat sur le rôle de l''État et de la société civile dans la protection sociale reste plus que jamais d''actualité. Une enquête d''opinion révèle que 76% des Français estiment que la solidarité est une valeur fondamentale qui devrait être davantage encouragée par les politiques publiques.

Question : Quel pourcentage de jeunes de 18-35 ans a participé à une action bénévole ?', NULL, '["52%", "58%", "62%", "68%"]', '62%', 1, 26, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('a9665938-8166-472c-b444-dcf2bc29e6ff', 'f61d727f-858f-42bf-93ef-72ad5fc0d77c', '### Les nouvelles solidarités face à la fragmentation du lien social

La société française contemporaine est traversée par des tensions qui interrogent la cohésion nationale. Entre individualisme croissant et fragmentation sociale, de nouvelles formes de solidarité émergent pourtant, témoignant d''une capacité de résilience collective. Les associations et les initiatives citoyennes se multiplient, notamment dans les domaines de l''aide alimentaire, du soutien scolaire et de l''accompagnement des personnes isolées. Il est remarquable que l''engagement citoyen se renouvelle malgré un contexte de défiance envers les institutions.

« On observe une véritable renaissance de l''engagement citoyen, particulièrement chez les jeunes générations », explique une sociologue spécialiste des mouvements associatifs. Selon une enquête récente, 62% des 18-35 ans déclarent avoir participé à au moins une action bénévole au cours des douze derniers mois, un chiffre en hausse constante depuis cinq ans. Il serait intéressant que les pouvoirs publics s''appuient davantage sur cet élan pour renforcer les politiques de cohésion sociale.

Les plateformes numériques jouent un rôle catalyseur dans cette recomposition du lien social, en facilitant la mise en relation des volontaires et des personnes dans le besoin. Cependant, des voix s''élèvent pour mettre en garde contre une « ubérisation » de la solidarité qui affaiblirait les services publics. Le débat sur le rôle de l''État et de la société civile dans la protection sociale reste plus que jamais d''actualité. Une enquête d''opinion révèle que 76% des Français estiment que la solidarité est une valeur fondamentale qui devrait être davantage encouragée par les politiques publiques.

Question : Quel est l''objectif de l''auteur en mentionnant que 76% des Français valorisent la solidarité ?', NULL, '["Souligner le décalage entre les valeurs affirmées et les politiques menées", "Démontrer que la solidarité est une valeur en déclin", "Prouver que les Français sont égoïstes", "Annoncer une nouvelle loi sur la solidarité"]', 'Souligner le décalage entre les valeurs affirmées et les politiques menées', 1, 27, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('732a091a-fca9-47f8-a5af-8a809b4aa324', '907602a7-d59c-4ad7-bebd-96d3e95bcf7c', '### Relevé de compte et nouvelles conditions tarifaires

Cher client, nous vous informons qu''à compter du 1er novembre, nos tarifs de gestion de compte évolueront. Les frais de tenue de compte passeront de 2,50€ à 3,00€ par mois. Cependant, pour les clients ayant souscrit à l''option ''Éco-Banque'', ces frais resteront inchangés. Nous vous rappelons que vous disposez d''un droit de résiliation sans frais si vous n''acceptez pas ces nouvelles conditions. Par ailleurs, notre nouvelle application mobile vous permet désormais de bloquer temporairement votre carte bancaire en cas de perte suspectée, offrant une sécurité accrue sans passer par notre service client téléphonique.

Question : Quelle est la nouvelle fonctionnalité de l''application ?', NULL, '["Le virement international", "Le blocage temporaire de la carte", "La commande de chéquiers", "L''ouverture de compte"]', 'Le blocage temporaire de la carte', 1, 28, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('34af66f1-bd4f-4639-9f2a-51817581ef2a', 'f61d727f-858f-42bf-93ef-72ad5fc0d77c', '### Système de santé : les défis de la médecine de demain face au vieillissement

Le système de santé français, longtemps considéré comme l''un des meilleurs au monde, traverse une période de turbulences sans précédent. La pénurie de personnel soignant, couplée au vieillissement de la population, exerce une pression croissante sur les hôpitaux publics. Selon un rapport du Haut Conseil de la santé publique, la France compterait 3,5 millions de personnes âgées dépendantes en 2030, soit une augmentation de 40% par rapport à 2020. Il est urgent que des mesures structurelles soient adoptées pour faire face à cette situation.

Face à cette situation, les pouvoirs publics misent sur la télémédecine et les innovations technologiques. « Les consultations à distance ont connu une augmentation de 500% depuis 2020, et cette tendance devrait se poursuivre », explique un chercheur en santé numérique. Le gouvernement a alloué une enveloppe de 500 millions d''euros pour moderniser les infrastructures hospitalières et développer les soins à domicile. Il faudrait que ces investissements soient pérennisés pour garantir leur efficacité à long terme.

Les professionnels de santé réclament quant à eux une revalorisation salariale et des conditions de travail plus attractives. « Il serait illusoire de vouloir réformer le système sans investir dans les ressources humaines », prévient un syndicat médical. La question du financement à long terme de la protection sociale demeure au cœur des débats politiques, d''autant que le vieillissement démographique devrait accroître les dépenses de santé de 1,5% par an en moyenne jusqu''en 2040, selon les projections de la Commission des comptes de la sécurité sociale.

Question : Quel est le sujet principal de cet article ?', NULL, '["Les défis du système de santé face au vieillissement de la population", "Les nouvelles techniques chirurgicales", "La fabrication de médicaments en France", "La formation des étudiants en médecine"]', 'Les défis du système de santé face au vieillissement de la population', 1, 29, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('7370e990-dd39-4b8b-8e48-ae421f5fd402', 'f61d727f-858f-42bf-93ef-72ad5fc0d77c', '### L''intelligence artificielle transforme le marché du travail : quelles perspectives ?

L''intelligence artificielle générative bouleverse les codes établis du monde professionnel, suscitant à la fois enthousiasme et inquiétude. Selon une étude prospective du Ministère du Travail, près de 30% des métiers actuels pourraient être profondément transformés par ces technologies d''ici 2030, tandis que de nouvelles professions émergeraient simultanément. Il est essentiel que les travailleurs anticipent ces mutations pour ne pas être pris au dépourvu.

Les secteurs les plus impactés seraient ceux de la traduction, du journalisme, de la programmation informatique et des services juridiques. « L''IA ne remplacera pas les humains, mais il est probable que les professionnels qui sauront exploiter ces outils remplaceront ceux qui les ignorent », affirme un expert en transformation numérique interrogé par nos confrères du Monde. Cette citation illustre bien le paradoxe auquel sont confrontés les travailleurs : il faudrait qu''ils se forment aux nouvelles technologies tout en conservant leur expertise métier.

Parallèlement, le gouvernement a annoncé un plan d''investissement de deux milliards d''euros pour former les travailleurs aux compétences numériques de demain. Ce programme ambitieux comprend notamment la création de cinquante campus dédiés à l''intelligence artificielle sur l''ensemble du territoire. Les syndicats restent toutefois vigilants quant aux conditions de mise en œuvre de cette transition technologique, craignant qu''elle ne se traduise par une précarisation accrue de certains emplois. Une enquête récente indique que 62% des salariés français se disent préoccupés par l''impact de l''IA sur leur travail.

Question : Pourquoi l''auteur cite-t-il l''expert en transformation numérique ?', NULL, '["Pour illustrer le paradoxe auquel sont confrontés les travailleurs", "Pour donner son opinion personnelle de manière indirecte", "Pour contredire les affirmations du gouvernement", "Pour annoncer une nouvelle technologie révolutionnaire"]', 'Pour illustrer le paradoxe auquel sont confrontés les travailleurs', 1, 30, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('5e7b5f3a-c08d-42ce-b20c-65062f011a17', 'f61d727f-858f-42bf-93ef-72ad5fc0d77c', '### L''intelligence artificielle transforme le marché du travail : quelles perspectives ?

L''intelligence artificielle générative bouleverse les codes établis du monde professionnel, suscitant à la fois enthousiasme et inquiétude. Selon une étude prospective du Ministère du Travail, près de 30% des métiers actuels pourraient être profondément transformés par ces technologies d''ici 2030, tandis que de nouvelles professions émergeraient simultanément. Il est essentiel que les travailleurs anticipent ces mutations pour ne pas être pris au dépourvu.

Les secteurs les plus impactés seraient ceux de la traduction, du journalisme, de la programmation informatique et des services juridiques. « L''IA ne remplacera pas les humains, mais il est probable que les professionnels qui sauront exploiter ces outils remplaceront ceux qui les ignorent », affirme un expert en transformation numérique interrogé par nos confrères du Monde. Cette citation illustre bien le paradoxe auquel sont confrontés les travailleurs : il faudrait qu''ils se forment aux nouvelles technologies tout en conservant leur expertise métier.

Parallèlement, le gouvernement a annoncé un plan d''investissement de deux milliards d''euros pour former les travailleurs aux compétences numériques de demain. Ce programme ambitieux comprend notamment la création de cinquante campus dédiés à l''intelligence artificielle sur l''ensemble du territoire. Les syndicats restent toutefois vigilants quant aux conditions de mise en œuvre de cette transition technologique, craignant qu''elle ne se traduise par une précarisation accrue de certains emplois. Une enquête récente indique que 62% des salariés français se disent préoccupés par l''impact de l''IA sur leur travail.

Question : Quelle attitude les syndicats adoptent-ils face à cette transition technologique ?', NULL, '["Ils sont vigilants et craignent une précarisation de certains emplois", "Ils s''opposent catégoriquement à toute introduction de l''IA", "Ils soutiennent sans réserve le plan gouvernemental", "Ils sont indifférents aux changements en cours"]', 'Ils sont vigilants et craignent une précarisation de certains emplois', 1, 31, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('2c4f5d57-da4e-4ca6-9c33-357c6768ad93', 'f61d727f-858f-42bf-93ef-72ad5fc0d77c', '### Les nouvelles solidarités face à la fragmentation du lien social

La société française contemporaine est traversée par des tensions qui interrogent la cohésion nationale. Entre individualisme croissant et fragmentation sociale, de nouvelles formes de solidarité émergent pourtant, témoignant d''une capacité de résilience collective. Les associations et les initiatives citoyennes se multiplient, notamment dans les domaines de l''aide alimentaire, du soutien scolaire et de l''accompagnement des personnes isolées. Il est remarquable que l''engagement citoyen se renouvelle malgré un contexte de défiance envers les institutions.

« On observe une véritable renaissance de l''engagement citoyen, particulièrement chez les jeunes générations », explique une sociologue spécialiste des mouvements associatifs. Selon une enquête récente, 62% des 18-35 ans déclarent avoir participé à au moins une action bénévole au cours des douze derniers mois, un chiffre en hausse constante depuis cinq ans. Il serait intéressant que les pouvoirs publics s''appuient davantage sur cet élan pour renforcer les politiques de cohésion sociale.

Les plateformes numériques jouent un rôle catalyseur dans cette recomposition du lien social, en facilitant la mise en relation des volontaires et des personnes dans le besoin. Cependant, des voix s''élèvent pour mettre en garde contre une « ubérisation » de la solidarité qui affaiblirait les services publics. Le débat sur le rôle de l''État et de la société civile dans la protection sociale reste plus que jamais d''actualité. Une enquête d''opinion révèle que 76% des Français estiment que la solidarité est une valeur fondamentale qui devrait être davantage encouragée par les politiques publiques.

Question : Que signifie « ubérisation de la solidarité » dans le contexte ?', NULL, '["La transformation de l''aide sociale en services marchands via des plateformes", "La généralisation des services de livraison à domicile", "La création d''une application de covoiturage solidaire", "La privatisation complète des services d''aide sociale"]', 'La transformation de l''aide sociale en services marchands via des plateformes', 1, 32, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('24558ed4-b306-4509-b5f4-98071e9b9749', '907602a7-d59c-4ad7-bebd-96d3e95bcf7c', '### L''impact de la 5G sur l''industrie manufacturière

Le déploiement de la 5G ne se limite pas à une augmentation de la vitesse pour les smartphones. Dans le secteur manufacturier, cette technologie permet l''avènement de ''l''usine intelligente''. Grâce à une latence extrêmement faible, les capteurs installés sur les chaînes de montage peuvent communiquer en temps réel avec des algorithmes d''IA pour prédire les pannes avant qu''elles ne surviennent. Cette maintenance prédictive réduit considérablement les temps d''arrêt et optimise la consommation énergétique. Néanmoins, l''adoption de la 5G nécessite des investissements massifs en infrastructure et une formation poussée des techniciens pour manipuler ces nouveaux outils numériques de haute précision.

Question : Quel est le principal avantage de la 5G pour les usines ?', NULL, '["Appeler les clients plus vite", "La communication en temps réel des capteurs", "Remplacer tous les ouvriers par des robots", "Baisser les salaires"]', 'La communication en temps réel des capteurs', 1, 33, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('3c105bde-12d4-4aed-8752-99e56e27a1de', '907602a7-d59c-4ad7-bebd-96d3e95bcf7c', '### L''impact de la 5G sur l''industrie manufacturière

Le déploiement de la 5G ne se limite pas à une augmentation de la vitesse pour les smartphones. Dans le secteur manufacturier, cette technologie permet l''avènement de ''l''usine intelligente''. Grâce à une latence extrêmement faible, les capteurs installés sur les chaînes de montage peuvent communiquer en temps réel avec des algorithmes d''IA pour prédire les pannes avant qu''elles ne surviennent. Cette maintenance prédictive réduit considérablement les temps d''arrêt et optimise la consommation énergétique. Néanmoins, l''adoption de la 5G nécessite des investissements massifs en infrastructure et une formation poussée des techniciens pour manipuler ces nouveaux outils numériques de haute précision.

Question : Quel est l''un des obstacles mentionnés ?', NULL, '["Le manque de signaux satellites", "Les investissements coûteux", "Le refus des consommateurs", "La météo"]', 'Les investissements coûteux', 1, 34, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('bf5bcbd6-1c3e-4a18-8cf7-27ed74303908', 'f61d727f-858f-42bf-93ef-72ad5fc0d77c', '### L''intelligence artificielle transforme le marché du travail : quelles perspectives ?

L''intelligence artificielle générative bouleverse les codes établis du monde professionnel, suscitant à la fois enthousiasme et inquiétude. Selon une étude prospective du Ministère du Travail, près de 30% des métiers actuels pourraient être profondément transformés par ces technologies d''ici 2030, tandis que de nouvelles professions émergeraient simultanément. Il est essentiel que les travailleurs anticipent ces mutations pour ne pas être pris au dépourvu.

Les secteurs les plus impactés seraient ceux de la traduction, du journalisme, de la programmation informatique et des services juridiques. « L''IA ne remplacera pas les humains, mais il est probable que les professionnels qui sauront exploiter ces outils remplaceront ceux qui les ignorent », affirme un expert en transformation numérique interrogé par nos confrères du Monde. Cette citation illustre bien le paradoxe auquel sont confrontés les travailleurs : il faudrait qu''ils se forment aux nouvelles technologies tout en conservant leur expertise métier.

Parallèlement, le gouvernement a annoncé un plan d''investissement de deux milliards d''euros pour former les travailleurs aux compétences numériques de demain. Ce programme ambitieux comprend notamment la création de cinquante campus dédiés à l''intelligence artificielle sur l''ensemble du territoire. Les syndicats restent toutefois vigilants quant aux conditions de mise en œuvre de cette transition technologique, craignant qu''elle ne se traduise par une précarisation accrue de certains emplois. Une enquête récente indique que 62% des salariés français se disent préoccupés par l''impact de l''IA sur leur travail.

Question : Quel est le montant du plan d''investissement gouvernemental pour la formation numérique ?', NULL, '["Un milliard d''euros", "Deux milliards d''euros", "Trois milliards d''euros", "Cinq cents millions d''euros"]', 'Deux milliards d''euros', 1, 35, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('0fda5c4b-4497-476d-8ca9-bca153ed88ef', 'f61d727f-858f-42bf-93ef-72ad5fc0d77c', '### La biodiversité en péril : l''urgence d''agir face à l''effondrement des écosystèmes

L''érosion de la biodiversité s''accélère à un rythme préoccupant, selon le dernier rapport du Groupe d''experts intergouvernemental sur l''évolution du climat (GIEC). Près d''un million d''espèces animales et végétales seraient menacées d''extinction à court terme, principalement en raison des activités humaines et du dérèglement climatique. Il est impératif que des mesures drastiques soient adoptées sans délai pour inverser cette tendance.

Face à ce constat alarmant, de nombreuses initiatives voient le jour tant au niveau local qu''international. La France a notamment annoncé le lancement d''un programme de restauration écologique portant sur 50 000 hectares de zones humides d''ici 2030. Ces écosystèmes, qui jouent un rôle crucial dans la régulation du climat et la filtration de l''eau, ont vu leur superficie diminuer de 67% au cours du siècle dernier. Il serait regrettable que les efforts ne soient pas à la hauteur de l''urgence.

Les scientifiques insistent sur la nécessité d''adopter une approche systémique. « Il ne suffit pas que nous protégions quelques espèces emblématiques ; il faut que nous préservions l''intégralité des écosystèmes dont dépend notre propre survie », explique une chercheuse du Muséum national d''histoire naturelle. Les décisions politiques prises dans les prochaines années seront déterminantes pour inverser cette tendance. Selon un sondage, 73% des citoyens européens considèrent que la protection de l''environnement devrait être une priorité absolue, ce qui témoigne d''une sensibilisation croissante de l''opinion publique.

Question : Quel est l''objectif de l''auteur en citant la chercheuse du Muséum ?', NULL, '["Apporter une crédibilité scientifique à l''argumentation", "Donner une opinion personnelle déguisée", "Présenter une position minoritaire dans le débat", "Critiquer les politiques gouvernementales actuelles"]', 'Apporter une crédibilité scientifique à l''argumentation', 1, 36, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('5d687f9b-8432-455d-8dcb-e800d9c5270b', 'f61d727f-858f-42bf-93ef-72ad5fc0d77c', '### L''école face aux défis du XXIe siècle : réformer pour mieux former

Le système éducatif français est engagé dans une vaste réforme visant à adapter l''enseignement aux enjeux contemporains. Au cœur de cette transformation, l''accent est mis sur l''apprentissage des langues étrangères, le développement des compétences numériques et l''éducation au développement durable. Il est indispensable que les élèves acquièrent les compétences qui leur permettront de s''épanouir dans un monde en constante évolution.

« Il convient que nos élèves soient préparés à évoluer dans un monde où les frontières professionnelles et géographiques sont de plus en plus poreuses », souligne un rapport de l''OCDE. Les résultats de la France aux évaluations internationales PISA, bien qu''en légère amélioration, demeurent inférieurs à la moyenne des pays comparables. Cette situation a motivé l''introduction de nouvelles méthodes pédagogiques, notamment l''enseignement par projet et l''évaluation par compétences. Il faudrait que les enseignants soient mieux formés à ces nouvelles approches pour qu''elles portent leurs fruits.

La réforme prévoit également la création de « cités éducatives » dans les quartiers prioritaires, visant à renforcer la coopération entre l''école, les familles et les acteurs locaux. Un budget supplémentaire de 800 millions d''euros a été débloqué pour réduire les effectifs dans les classes et améliorer l''équité territoriale. Le taux de décrochage scolaire, qui touche encore près de 8% des jeunes Français, est jugé préoccupant par les syndicats enseignants. Selon une enquête, 64% des parents estiment que l''école devrait accorder une place plus importante à l''éducation aux médias et à l''information.

Question : Quel est le budget supplémentaire débloqué pour la réforme éducative ?', NULL, '["500 millions d''euros", "600 millions d''euros", "800 millions d''euros", "1 milliard d''euros"]', '800 millions d''euros', 1, 37, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('7f0acecb-f6d5-4c7e-8367-1ac5b9bff128', '907602a7-d59c-4ad7-bebd-96d3e95bcf7c', '### Apprentissage des langues par immersion

L''immersion totale est reconnue comme la méthode la plus efficace pour acquérir une compétence linguistique durable. Contrairement à l''apprentissage théorique, elle force le cerveau à traiter l''information en contexte réel, favorisant la plasticité neuronale. Les participants à nos programmes d''immersion à Montréal témoignent d''une progression fulgurante de leur compréhension orale et de leur aisance à l''oral en seulement quatre semaines. Cependant, cette méthode exige un investissement personnel important et une acceptation de l''erreur comme faisant partie intégrante du processus d''apprentissage.

Question : Quelle attitude est recommandée aux apprenants ?', NULL, '["Vouloir être parfait tout de suite", "Accepter de faire des erreurs", "Étudier uniquement la grammaire", "Éviter de parler aux locaux"]', 'Accepter de faire des erreurs', 1, 38, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('eb37c538-b551-4220-9f2f-e03990420658', 'f61d727f-858f-42bf-93ef-72ad5fc0d77c', '### L''économie française face aux défis de la transition énergétique

La transition énergétique représente à la fois un défi et une opportunité pour l''économie française. Alors que le gouvernement a fixé l''objectif ambitieux d''atteindre la neutralité carbone d''ici 2050, les entreprises doivent désormais repenser leurs modèles d''affaires pour s''adapter à cette nouvelle donne. Encore faudrait-il que les investissements nécessaires suivent le rythme des ambitions affichées.

Selon un rapport récent de l''Observatoire des investissements verts, les montants alloués aux énergies renouvelables ont augmenté de 35% au cours des deux dernières années, témoignant d''une prise de conscience collective. Néanmoins, certains secteurs industriels, notamment l''automobile et la sidérurgie, peinent à opérer leur mue écologique sans compromettre leur compétitivité sur le marché international. Le président d''un grand groupe industriel a récemment déclaré qu''il serait indispensable que l''Union européenne assouplisse temporairement certaines normes environnementales pour permettre une transition en douceur.

Les économistes s''interrogent sur la capacité de la France à concilier impératifs écologiques et croissance économique. « Il faudrait que les pouvoirs publics accompagnent davantage les PME dans cette transition, car elles représentent le tissu économique le plus vulnérable », souligne une étude de la Banque de France. Les prochaines années seront décisives pour déterminer si cette transformation structurelle portera ses fruits, d''autant que la facture énergétique des ménages continue d''augmenter, ce qui suscite des inquiétudes quant à l''acceptabilité sociale de ces réformes.

Question : Quel est le ton général de cet article ?', NULL, '["Neutre et informatif, présentant différents points de vue", "Alarmiste et catastrophiste sur l''avenir économique", "Optimiste et enthousiaste quant aux progrès réalisés", "Sarcastique et critique envers les politiques environnementales"]', 'Neutre et informatif, présentant différents points de vue', 1, 39, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('41ec3208-f30a-45ab-b35b-280f6521e9bb', 'd741196d-4619-4229-b20f-358301f30e9e', 'Quel est le sujet du débat ?', NULL, '["Les salaires", "Le télétravail", "La retraite", "Le temps de transport"]', 'Le télétravail', 1, 0, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('0128c85a-6f15-4505-b638-b074c0442771', 'd741196d-4619-4229-b20f-358301f30e9e', 'Quel est le métier de l''invité ?', NULL, '["Journaliste", "Commerçant", "Urbaniste", "Maire"]', 'Urbaniste', 1, 1, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('ec1a353f-cd4f-402f-b4f8-865ebf568213', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'Quelle consigne est donnée aux conducteurs ?', NULL, '["Rouler prudemment", "Reporter les déplacements", "Mettre des pneus d''été", "Prendre le bus"]', 'Reporter les déplacements', 1, 2, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('7d1ca3e2-4094-4c52-ad87-8ede4de97c8e', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'D''après ce message téléphonique se déroulant dans un(e) banque, quelle est l''information principale ?', NULL, '["Option A", "Option B", "Option C", "Option D"]', 'Option A', 1, 3, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('066fb4c5-13f2-42ce-93e9-c981484c1e90', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'D''après ce annonce publique se déroulant dans un(e) gare, quelle est l''information principale ?', NULL, '["Option A", "Option B", "Option C", "Option D"]', 'Option A', 1, 4, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('a027bd6d-b96f-48e5-8b7c-5e5a92d0e580', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'D''après ce message téléphonique se déroulant dans un(e) cinema, quelle est l''information principale ?', NULL, '["Option A", "Option B", "Option C", "Option D"]', 'Option A', 1, 5, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('844e0462-c38a-4441-b50d-9ad1371ce261', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'D''après ce extrait radio se déroulant dans un(e) rue, quelle est l''information principale ?', NULL, '["Option A", "Option B", "Option C", "Option D"]', 'Option A', 1, 6, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('639250c1-4c4f-4de9-82b1-ca1c04ddfae8', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'Quels articles sont en promotion ?', NULL, '["Tous les articles", "Les articles avec pastille rouge", "Uniquement les chaussures", "Les articles d''été"]', 'Les articles avec pastille rouge', 1, 7, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('e3e6dc16-8524-4f43-9f99-562137ee0843', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'Pourquoi y a-t-il une liquidation ?', NULL, '["Fermeture définitive", "Avant travaux", "Changement de propriétaire", "Fin de saison"]', 'Avant travaux', 1, 8, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('75d888db-873a-4967-a0b9-f988347c02c2', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'À quelle heure le musée ferme-t-il ?', NULL, '["17h", "18h", "19h", "20h"]', '17h', 1, 9, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('fe2b31d5-e5de-4c03-9da6-d2a86fdf01ae', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'D''après ce conversation courte se déroulant dans un(e) gare, quelle est l''information principale ?', NULL, '["Option A", "Option B", "Option C", "Option D"]', 'Option A', 1, 10, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('1ee2992b-8a53-4b6a-a1f7-0625457791fd', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'D''après ce message téléphonique se déroulant dans un(e) cinema, quelle est l''information principale ?', NULL, '["Option A", "Option B", "Option C", "Option D"]', 'Option A', 1, 11, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('4df31848-eb5b-4f36-b940-b0d5431210e7', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'À quelle heure est le rendez-vous ?', NULL, '["10h", "14h", "15h", "16h"]', '15h', 1, 12, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('c6788550-ab67-4253-ae69-13731f1b9f85', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'D''après ce annonce publique se déroulant dans un(e) gare, quelle est l''information principale ?', NULL, '["Option A", "Option B", "Option C", "Option D"]', 'Option A', 1, 13, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('b8e4f73d-cb01-441a-b716-1fccc1582392', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'Pourquoi Julie appelle-t-elle ?', NULL, '["Pour un projet de vacances", "Pour un poste de graphiste", "Pour annuler un rendez-vous", "Pour emprunter de l''argent"]', 'Pour un poste de graphiste', 1, 14, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('ff20018d-ff90-429b-9134-6426e2f1d980', 'd741196d-4619-4229-b20f-358301f30e9e', 'Quelle est la position du deuxième locuteur ?', NULL, '["Totalement favorable", "Totalement opposé", "Nuancée avec une préférence pour le bureau", "Il ne s''exprime pas"]', 'Nuancée avec une préférence pour le bureau', 1, 15, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('6441aa08-b799-46ba-b3c8-fdd3ae00c2eb', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'D''après ce conversation courte se déroulant dans un(e) magasin, quelle est l''information principale ?', NULL, '["Option A", "Option B", "Option C", "Option D"]', 'Option A', 1, 16, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('dbce061a-0e6a-4d0e-bfa4-d39a7ae06c8e', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'D''après ce annonce publique se déroulant dans un(e) hopital, quelle est l''information principale ?', NULL, '["Option A", "Option B", "Option C", "Option D"]', 'Option A', 1, 17, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('a787c3a7-87c4-49eb-9504-1bdb66f7cf61', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'D''après ce conversation courte se déroulant dans un(e) ecole, quelle est l''information principale ?', NULL, '["Option A", "Option B", "Option C", "Option D"]', 'Option A', 1, 18, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('e1ee31ff-58a4-495b-966d-8b920da29e92', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'D''après ce annonce publique se déroulant dans un(e) gare, quelle est l''information principale ?', NULL, '["Option A", "Option B", "Option C", "Option D"]', 'Option A', 1, 19, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('a2dcd021-afc7-4dd4-b551-cd1c7c590cbc', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'D''après ce extrait radio se déroulant dans un(e) bureau, quelle est l''information principale ?', NULL, '["Option A", "Option B", "Option C", "Option D"]', 'Option A', 1, 20, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('c3988b23-0545-471c-b9ad-5eaeaed92e27', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'Quelle est la destination finale du train ?', NULL, '["Montréal", "Toronto", "Kingston", "Ottawa"]', 'Toronto', 1, 21, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('2fbc08f3-e674-4dd3-9c72-3f8e3d5d1916', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'D''après ce extrait radio se déroulant dans un(e) maison, quelle est l''information principale ?', NULL, '["Option A", "Option B", "Option C", "Option D"]', 'Option A', 1, 22, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('9e8987b3-434f-4ba9-85c9-52198256ab6f', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'D''après ce extrait radio se déroulant dans un(e) banque, quelle est l''information principale ?', NULL, '["Option A", "Option B", "Option C", "Option D"]', 'Option A', 1, 23, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('ea2975e9-b6bd-43dc-a786-03ab83290865', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'D''après ce annonce publique se déroulant dans un(e) restaurant, quelle est l''information principale ?', NULL, '["Option A", "Option B", "Option C", "Option D"]', 'Option A', 1, 24, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('d4b32781-7aeb-4b82-9334-b4ed49c823d3', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'D''après ce message téléphonique se déroulant dans un(e) maison, quelle est l''information principale ?', NULL, '["Option A", "Option B", "Option C", "Option D"]', 'Option A', 1, 25, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('dae6f066-4440-47cc-8f75-3d26788f0f44', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'D''après ce annonce publique se déroulant dans un(e) restaurant, quelle est l''information principale ?', NULL, '["Option A", "Option B", "Option C", "Option D"]', 'Option A', 1, 26, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('6ecebbc4-fe4c-4ea9-b1a6-8cfc55e3f01f', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'D''après ce conversation courte se déroulant dans un(e) magasin, quelle est l''information principale ?', NULL, '["Option A", "Option B", "Option C", "Option D"]', 'Option A', 1, 27, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('8e374c94-d2e7-4c63-adf8-b4c2620e6326', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'D''après ce conversation courte se déroulant dans un(e) restaurant, quelle est l''information principale ?', NULL, '["Option A", "Option B", "Option C", "Option D"]', 'Option A', 1, 28, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('9aff4346-c98c-4052-b6a8-4bd713252268', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'D''après ce message téléphonique se déroulant dans un(e) rue, quelle est l''information principale ?', NULL, '["Option A", "Option B", "Option C", "Option D"]', 'Option A', 1, 29, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('c4ff75cb-c6aa-45f4-9517-24059868fd4d', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'D''après ce extrait radio se déroulant dans un(e) banque, quelle est l''information principale ?', NULL, '["Option A", "Option B", "Option C", "Option D"]', 'Option A', 1, 30, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('e79a42b2-45eb-49d6-8095-01a8ed29a983', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'D''après ce message téléphonique se déroulant dans un(e) rue, quelle est l''information principale ?', NULL, '["Option A", "Option B", "Option C", "Option D"]', 'Option A', 1, 31, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('432301ea-cf4b-4b09-9a0b-d26687a452ff', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'D''après ce message téléphonique se déroulant dans un(e) maison, quelle est l''information principale ?', NULL, '["Option A", "Option B", "Option C", "Option D"]', 'Option A', 1, 32, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('68aa193b-1b53-4e09-ab87-8e7bf43861e6', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'Pourquoi le train est-il en retard ?', NULL, '["Problème météo", "Incident technique", "Travaux sur la voie", "Grève"]', 'Travaux sur la voie', 1, 33, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('8f575f66-d73e-40db-9b7f-e28609fb9813', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'D''après ce annonce publique se déroulant dans un(e) magasin, quelle est l''information principale ?', NULL, '["Option A", "Option B", "Option C", "Option D"]', 'Option A', 1, 34, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('527939e5-75c7-4c3d-8d1b-361211315f7c', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'Jusqu''à quelle heure est-elle disponible ?', NULL, '["15h", "16h", "17h", "18h"]', '17h', 1, 35, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('e63d6b99-d08e-49f4-9d31-ae26e376543c', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'D''après ce annonce publique se déroulant dans un(e) ecole, quelle est l''information principale ?', NULL, '["Option A", "Option B", "Option C", "Option D"]', 'Option A', 1, 36, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('bc9c966f-5265-4022-bf6e-b60080b570e1', 'd741196d-4619-4229-b20f-358301f30e9e', 'Quelle est la principale crainte des commerçants ?', NULL, '["Le bruit", "La pollution", "La perte de clients automobilistes", "Les taxes"]', 'La perte de clients automobilistes', 1, 37, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('ae3ba4c8-81c2-46cb-90b7-68df2be39090', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'D''après ce extrait radio se déroulant dans un(e) cinema, quelle est l''information principale ?', NULL, '["Option A", "Option B", "Option C", "Option D"]', 'Option A', 1, 38, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('b8203456-2601-4e54-bfd6-87f588a6646f', 'd72182b6-ee87-4394-857d-052ce2b05a12', 'D''après ce conversation courte se déroulant dans un(e) magasin, quelle est l''information principale ?', NULL, '["Option A", "Option B", "Option C", "Option D"]', 'Option A', 1, 39, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('d6378482-bfb2-4549-ba7b-d42c71c6823e', '319775b5-56bf-458c-8b60-1f3c7913daa4', '### Section A : Fait divers (80 mots minimum)

Vous avez été témoin d''une scène insolite dans un parc public. Rédigez un court article pour le journal local relatant les faits de manière objective.', NULL, NULL, NULL, 10, 0, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('cfab1b0b-760c-41ef-97a1-2ae63def2aa1', '319775b5-56bf-458c-8b60-1f3c7913daa4', '### Section B : Lettre d''argumentation (200 mots minimum)

La direction de votre espace de coworking a décidé de supprimer le service de café gratuit pour réduire les coûts. Écrivez une lettre au gestionnaire pour exprimer votre désaccord en argumentant sur l''impact pour la communauté des travailleurs.', NULL, NULL, NULL, 20, 1, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('b7cbdd92-bbc8-47d6-9393-d47049ab7b42', 'a2a4037a-814b-46f8-a768-b8b8dcefc649', '### Section A : S''informer sur un service

Vous avez vu une annonce pour un service de garde d''animaux à domicile. Appelez l''annonceur et posez 10 questions précises sur le fonctionnement, les tarifs et l''expérience.', NULL, NULL, NULL, 10, 0, '2026-07-18T04:14:18.091031');
INSERT INTO test_questions (id, test_id, question_text, audio_url, options, correct_answer, points, order_index, created_at) VALUES ('d1738b29-82f8-4f1f-8925-13916721f80c', 'a2a4037a-814b-46f8-a768-b8b8dcefc649', '### Section B : Convaincre un proche

Un ami hésite à participer à un marathon de bienfaisance. Essayez de le convaincre en mettant en avant les bienfaits personnels et l''impact social de l''événement.', NULL, NULL, NULL, 20, 1, '2026-07-18T04:14:18.091031');
