const { createClient } = require('@supabase/supabase-js');

const supabase = createClient(
  'https://yqeyxmpuftcaujsuyyyj.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxZXl4bXB1ZnRjYXVqc3V5eXlqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NDA2ODE1NCwiZXhwIjoyMDk5NjQ0MTU0fQ.1apQqk9pXSkjpLLMbDpkCJa-ixY9PntddjOhnn12ceE'
);

const allQuestions = [
  // READING 1: Vie quotidienne au Canada (10 questions)
  {id:"1136ebf9-30ff-478e-9712-e98dbd6334ef",test_id:"c8ac4595-2def-42f1-8ba8-86f9ed4de91f",question_text:"Au Canada, le bénévolat est considéré comme un pilier de la société. Chaque année, des millions de Canadiens consacrent de leur temps pour aider des organisations caritatives, des écoles ou des centres communautaires. Pour les nouveaux arrivants, le bénévolat est souvent recommandé non seulement pour contribuer à la communauté, mais aussi pour acquérir une première expérience canadienne, développer son réseau professionnel et améliorer ses compétences linguistiques.\n\nQuestion : Quel est l'un des avantages du bénévolat pour les nouveaux arrivants ?",options:["Recevoir un salaire élevé","Acquérir une expérience canadienne","Obtenir la citoyenneté immédiatement","Éviter de payer des impôts"],correct_answer:"Acquérir une expérience canadienne",points:1,order_index:0},
  {id:"cfe06093-b19b-40a7-b383-a35a805c78fc",test_id:"c8ac4595-2def-42f1-8ba8-86f9ed4de91f",question_text:"Au Canada, le bénévolat est considéré comme un pilier de la société. Chaque année, des millions de Canadiens consacrent de leur temps pour aider des organisations caritatives, des écoles ou des centres communautaires. Pour les nouveaux arrivants, le bénévolat est souvent recommandé non seulement pour contribuer à la communauté, mais aussi pour acquérir une première expérience canadienne, développer son réseau professionnel et améliorer ses compétences linguistiques.\n\nQuestion : Selon le texte, le bénévolat est :",options:["Une obligation légale","Une perte de temps","Un pilier de la société canadienne","Réservé aux retraités"],correct_answer:"Un pilier de la société canadienne",points:1,order_index:1},
  {id:"c0e70dba-f5bc-457c-b2ec-18ec9d04eb32",test_id:"c8ac4595-2def-42f1-8ba8-86f9ed4de91f",question_text:"Montréal dispose d'un réseau de transport en commun efficace géré par la STM. Il comprend quatre lignes de métro identifiées par des couleurs et des centaines de lignes de bus. Les usagers peuvent utiliser la carte OPUS pour charger leurs titres de transport. Pendant l'hiver, le métro est particulièrement apprécié car il permet de se déplacer à l'abri du froid intense grâce au réseau souterrain qui relie de nombreux édifices du centre-ville.\n\nQuestion : Comment s'appelle la carte de transport à Montréal ?",options:["La carte STM","La carte METRO","La carte OPUS","La carte VOYAGE"],correct_answer:"La carte OPUS",points:1,order_index:2},
  {id:"0fe6811c-a271-4c2d-84de-27b5b7561dd9",test_id:"c8ac4595-2def-42f1-8ba8-86f9ed4de91f",question_text:"Montréal dispose d'un réseau de transport en commun efficace géré par la STM. Il comprend quatre lignes de métro identifiées par des couleurs et des centaines de lignes de bus. Les usagers peuvent utiliser la carte OPUS pour charger leurs titres de transport. Pendant l'hiver, le métro est particulièrement apprécié car il permet de se déplacer à l'abri du froid intense grâce au réseau souterrain qui relie de nombreux édifices du centre-ville.\n\nQuestion : Pourquoi le métro est-il avantageux en hiver ?",options:["Il est gratuit","Il est plus rapide qu'en été","Il permet d'éviter le froid","Il y a moins de monde"],correct_answer:"Il permet d'éviter le froid",points:1,order_index:3},
  {id:"a1b2c3d4-1111-4000-8000-100000000001",test_id:"c8ac4595-2def-42f1-8ba8-86f9ed4de91f",question_text:"Le système de santé canadien, connu sous le nom d'assurance-maladie, est financé par les impôts et offre un accès gratuit aux services médicaux essentiels. Chaque province gère son propre régime d'assurance-santé. Les nouveaux arrivants doivent généralement attendre jusqu'à trois mois avant d'être admissibles, selon la province. Il est fortement recommandé de souscrire une assurance privée pour couvrir cette période d'attente.\n\nQuestion : Combien de temps les nouveaux arrivants doivent-ils généralement attendre pour être admissibles à l'assurance-maladie ?",options:["Une semaine","Un mois","Jusqu'à trois mois","Un an"],correct_answer:"Jusqu'à trois mois",points:1,order_index:4},
  {id:"a1b2c3d4-2222-4000-8000-200000000002",test_id:"c8ac4595-2def-42f1-8ba8-86f9ed4de91f",question_text:"Le système de santé canadien, connu sous le nom d'assurance-maladie, est financé par les impôts et offre un accès gratuit aux services médicaux essentiels. Chaque province gère son propre régime d'assurance-santé. Les nouveaux arrivants doivent généralement attendre jusqu'à trois mois avant d'être admissibles, selon la province. Il est fortement recommandé de souscrire une assurance privée pour couvrir cette période d'attente.\n\nQuestion : Que recommande-t-on aux nouveaux arrivants pendant la période d'attente ?",options:["D'attendre sans rien faire","De retourner dans leur pays","De souscrire une assurance privée","De changer de province"],correct_answer:"De souscrire une assurance privée",points:1,order_index:5},
  {id:"a1b2c3d4-3333-4000-8000-300000000003",test_id:"c8ac4595-2def-42f1-8ba8-86f9ed4de91f",question_text:"L'hiver canadien est réputé pour ses températures extrêmes qui peuvent descendre sous les -30°C dans certaines régions. Pour affronter cette saison, les Canadiens adoptent le principe des « trois couches » : une couche de base qui évacue l'humidité, une couche isolante qui retient la chaleur, et une couche extérieure coupe-vent et imperméable. Les tuques, gants et bottes isolées ne sont pas seulement des accessoires de mode — ils sont essentiels pour éviter les engelures.\n\nQuestion : Selon le texte, les tuques et les gants sont :",options:["Des accessoires de mode uniquement","Essentiels pour éviter les engelures","Optionnels en hiver","Recommandés seulement pour les enfants"],correct_answer:"Essentiels pour éviter les engelures",points:1,order_index:6},
  {id:"a1b2c3d4-4444-4000-8000-400000000004",test_id:"c8ac4595-2def-42f1-8ba8-86f9ed4de91f",question_text:"L'hiver canadien est réputé pour ses températures extrêmes qui peuvent descendre sous les -30°C dans certaines régions. Pour affronter cette saison, les Canadiens adoptent le principe des « trois couches » : une couche de base qui évacue l'humidité, une couche isolante qui retient la chaleur, et une couche extérieure coupe-vent et imperméable. Les tuques, gants et bottes isolées ne sont pas seulement des accessoires de mode — ils sont essentiels pour éviter les engelures.\n\nQuestion : Quel est le rôle de la couche extérieure dans le système des trois couches ?",options:["Évacuer l'humidité","Retenir la chaleur","Protéger du vent et de l'eau","Être à la mode"],correct_answer:"Protéger du vent et de l'eau",points:1,order_index:7},
  {id:"a1b2c3d4-5555-4000-8000-500000000005",test_id:"c8ac4595-2def-42f1-8ba8-86f9ed4de91f",question_text:"Au Canada, le pourboire fait partie intégrante de la culture de service. Dans les restaurants, il est d'usage de laisser entre 15% et 20% du montant avant taxes. Les coiffeurs, chauffeurs de taxi et livreurs s'attendent également à recevoir un pourboire. Cette pratique s'explique en partie par le fait que le salaire minimum des emplois à pourboire est souvent inférieur au salaire minimum régulier.\n\nQuestion : Quel pourcentage de pourboire est habituel dans les restaurants canadiens ?",options:["5% à 10%","10% à 12%","15% à 20%","25% à 30%"],correct_answer:"15% à 20%",points:1,order_index:8},
  {id:"a1b2c3d4-6666-4000-8000-600000000006",test_id:"c8ac4595-2def-42f1-8ba8-86f9ed4de91f",question_text:"Au Canada, le pourboire fait partie intégrante de la culture de service. Dans les restaurants, il est d'usage de laisser entre 15% et 20% du montant avant taxes. Les coiffeurs, chauffeurs de taxi et livreurs s'attendent également à recevoir un pourboire. Cette pratique s'explique en partie par le fait que le salaire minimum des emplois à pourboire est souvent inférieur au salaire minimum régulier.\n\nQuestion : Pourquoi le pourboire est-il important selon le texte ?",options:["Parce que c'est obligatoire par la loi","Parce que le salaire minimum à pourboire est souvent inférieur","Parce que les Canadiens sont riches","Parce que les restaurants ne paient pas leurs employés"],correct_answer:"Parce que le salaire minimum à pourboire est souvent inférieur",points:1,order_index:9},

  // READING 2: Emploi et Formation (10 questions)
  {id:"36021076-a3b7-4801-a6b9-577e4dee9446",test_id:"b5b66464-d654-4e94-ac67-0e1f342469bc",question_text:"L'un des défis majeurs pour les immigrants qualifiés au Canada est la reconnaissance de leurs diplômes obtenus à l'étranger. Plusieurs organismes provinciaux sont chargés d'évaluer les études effectuées hors du pays pour établir une équivalence avec le système éducatif canadien. Cette étape est souvent cruciale pour accéder à certaines professions réglementées, comme l'ingénierie, la santé ou l'enseignement, qui exigent d'être membre d'un ordre professionnel.\n\nQuestion : Quel est le but de l'évaluation des diplômes étrangers ?",options:["Annuler les diplômes","Établir une équivalence avec le système canadien","Traduire les documents","Augmenter les frais d'inscription"],correct_answer:"Établir une équivalence avec le système canadien",points:1,order_index:0},
  {id:"57bbc2ee-e4d1-42bd-8c76-a75220653c51",test_id:"b5b66464-d654-4e94-ac67-0e1f342469bc",question_text:"L'un des défis majeurs pour les immigrants qualifiés au Canada est la reconnaissance de leurs diplômes obtenus à l'étranger. Plusieurs organismes provinciaux sont chargés d'évaluer les études effectuées hors du pays pour établir une équivalence avec le système éducatif canadien. Cette étape est souvent cruciale pour accéder à certaines professions réglementées, comme l'ingénierie, la santé ou l'enseignement, qui exigent d'être membre d'un ordre professionnel.\n\nQuestion : Quelles professions exigent souvent d'être membre d'un ordre professionnel ?",options:["Toutes les professions sans exception","Uniquement les métiers manuels","Les professions réglementées comme l'ingénierie et la santé","Le bénévolat"],correct_answer:"Les professions réglementées comme l'ingénierie et la santé",points:1,order_index:1},
  {id:"b2c3d4e5-1111-4000-8000-100000000001",test_id:"b5b66464-d654-4e94-ac67-0e1f342469bc",question_text:"Le marché du travail canadien valorise grandement le réseautage professionnel. On estime que près de 65% des emplois ne sont jamais affichés publiquement et sont pourvus par le bouche-à-oreille ou des recommandations. Les événements de réseautage, les salons de l'emploi et les plateformes comme LinkedIn sont devenus des outils indispensables pour les chercheurs d'emploi. Pour les nouveaux arrivants, rejoindre des associations professionnelles et participer à des événements communautaires peut considérablement accélérer leur intégration au marché du travail.\n\nQuestion : Quel pourcentage d'emplois n'est jamais affiché publiquement selon le texte ?",options:["25%","45%","65%","85%"],correct_answer:"65%",points:1,order_index:2},
  {id:"b2c3d4e5-2222-4000-8000-200000000002",test_id:"b5b66464-d654-4e94-ac67-0e1f342469bc",question_text:"Le marché du travail canadien valorise grandement le réseautage professionnel. On estime que près de 65% des emplois ne sont jamais affichés publiquement et sont pourvus par le bouche-à-oreille ou des recommandations. Les événements de réseautage, les salons de l'emploi et les plateformes comme LinkedIn sont devenus des outils indispensables pour les chercheurs d'emploi. Pour les nouveaux arrivants, rejoindre des associations professionnelles et participer à des événements communautaires peut considérablement accélérer leur intégration au marché du travail.\n\nQuestion : Que recommande le texte aux nouveaux arrivants ?",options:["De rester chez eux","De rejoindre des associations professionnelles","D'éviter les événements","De ne pas utiliser LinkedIn"],correct_answer:"De rejoindre des associations professionnelles",points:1,order_index:3},
  {id:"b2c3d4e5-3333-4000-8000-300000000003",test_id:"b5b66464-d654-4e94-ac67-0e1f342469bc",question_text:"Au Canada, le curriculum vitae (CV) diffère sensiblement du modèle européen. Les employeurs canadiens s'attendent à un CV concis de deux pages maximum, mettant l'accent sur les réalisations mesurables plutôt que sur une simple liste de responsabilités. Il est également recommandé de ne pas inclure de photo, d'âge ou de situation familiale, car ces informations pourraient être source de discrimination involontaire. Une lettre de présentation personnalisée est presque toujours exigée pour accompagner la candidature.\n\nQuestion : Quelle est la longueur recommandée d'un CV canadien ?",options:["Une page maximum","Deux pages maximum","Trois pages","Autant de pages que nécessaire"],correct_answer:"Deux pages maximum",points:1,order_index:4},
  {id:"b2c3d4e5-4444-4000-8000-400000000004",test_id:"b5b66464-d654-4e94-ac67-0e1f342469bc",question_text:"Au Canada, le curriculum vitae (CV) diffère sensiblement du modèle européen. Les employeurs canadiens s'attendent à un CV concis de deux pages maximum, mettant l'accent sur les réalisations mesurables plutôt que sur une simple liste de responsabilités. Il est également recommandé de ne pas inclure de photo, d'âge ou de situation familiale, car ces informations pourraient être source de discrimination involontaire. Une lettre de présentation personnalisée est presque toujours exigée pour accompagner la candidature.\n\nQuestion : Pourquoi déconseille-t-on d'inclure une photo dans son CV au Canada ?",options:["Parce que c'est illégal","Pour éviter toute discrimination","Par manque de place","Par tradition"],correct_answer:"Pour éviter toute discrimination",points:1,order_index:5},
  {id:"b2c3d4e5-5555-4000-8000-500000000005",test_id:"b5b66464-d654-4e94-ac67-0e1f342469bc",question_text:"Les programmes d'alternance travail-études, appelés « coop » au Canada, permettent aux étudiants d'alterner entre des sessions académiques et des stages rémunérés en entreprise. Ces programmes sont très prisés car ils offrent une expérience professionnelle concrète tout en poursuivant ses études. Les étudiants en programme coop ont souvent un avantage significatif sur le marché du travail après l'obtention de leur diplôme, car ils possèdent déjà un réseau professionnel et des références.\n\nQuestion : Qu'est-ce qu'un programme « coop » ?",options:["Un programme d'échange linguistique","Une alternance travail-études","Un cours de coopération internationale","Un stage non rémunéré"],correct_answer:"Une alternance travail-études",points:1,order_index:6},
  {id:"b2c3d4e5-6666-4000-8000-600000000006",test_id:"b5b66464-d654-4e94-ac67-0e1f342469bc",question_text:"Les programmes d'alternance travail-études, appelés « coop » au Canada, permettent aux étudiants d'alterner entre des sessions académiques et des stages rémunérés en entreprise. Ces programmes sont très prisés car ils offrent une expérience professionnelle concrète tout en poursuivant ses études. Les étudiants en programme coop ont souvent un avantage significatif sur le marché du travail après l'obtention de leur diplôme, car ils possèdent déjà un réseau professionnel et des références.\n\nQuestion : Quel avantage les étudiants coop ont-ils après le diplôme ?",options:["Ils n'ont pas besoin de travailler","Ils possèdent déjà un réseau et des références","Ils sont automatiquement embauchés","Ils reçoivent un salaire plus élevé garanti"],correct_answer:"Ils possèdent déjà un réseau et des références",points:1,order_index:7},
  {id:"b2c3d4e5-7777-4000-8000-700000000007",test_id:"b5b66464-d654-4e94-ac67-0e1f342469bc",question_text:"L'entrevue d'embauche au Canada suit souvent un format standardisé appelé « entrevue comportementale ». Les recruteurs posent des questions basées sur des situations passées, comme « Parlez-moi d'une fois où vous avez résolu un conflit au travail ». La méthode STAR (Situation, Tâche, Action, Résultat) est recommandée pour structurer ses réponses. Il est également attendu que le candidat pose des questions pertinentes sur l'entreprise à la fin de l'entrevue.\n\nQuestion : Quel format d'entrevue est courant au Canada ?",options:["L'entrevue téléphonique","L'entrevue de groupe","L'entrevue comportementale","L'entrevue surprise"],correct_answer:"L'entrevue comportementale",points:1,order_index:8},
  {id:"b2c3d4e5-8888-4000-8000-800000000008",test_id:"b5b66464-d654-4e94-ac67-0e1f342469bc",question_text:"L'entrevue d'embauche au Canada suit souvent un format standardisé appelé « entrevue comportementale ». Les recruteurs posent des questions basées sur des situations passées, comme « Parlez-moi d'une fois où vous avez résolu un conflit au travail ». La méthode STAR (Situation, Tâche, Action, Résultat) est recommandée pour structurer ses réponses. Il est également attendu que le candidat pose des questions pertinentes sur l'entreprise à la fin de l'entrevue.\n\nQuestion : Que signifie l'acronyme STAR ?",options:["Situation, Tâche, Action, Résultat","Salaire, Travail, Ambition, Retraite","Sérieux, Talent, Attitude, Respect","Stage, Test, Apprentissage, Recrutement"],correct_answer:"Situation, Tâche, Action, Résultat",points:1,order_index:9},

  // LISTENING 1: Transports (10 questions)
  {id:"dd10e9fa-56fb-4f29-9aa6-ac30bbbe355a",test_id:"a680f24e-7138-45b3-8698-a4007dd050d0",question_text:"Mesdames et messieurs, votre attention s'il vous plaît. Le train VIA Rail numéro 64 en provenance de Toronto et à destination de Montréal aura un retard d'environ 30 minutes en raison de travaux sur la voie. Nous nous excusons pour les inconvénients que cela pourrait causer.\n\nQuestion : D'où vient le train ?",options:["Montréal","Ottawa","Toronto","Québec"],correct_answer:"Toronto",points:1,order_index:0},
  {id:"9c860c8f-1a84-4e47-8a1c-2a0a4ba96e98",test_id:"a680f24e-7138-45b3-8698-a4007dd050d0",question_text:"Mesdames et messieurs, votre attention s'il vous plaît. Le train VIA Rail numéro 64 en provenance de Toronto et à destination de Montréal aura un retard d'environ 30 minutes en raison de travaux sur la voie. Nous nous excusons pour les inconvénients que cela pourrait causer.\n\nQuestion : Quelle est la durée du retard prévu ?",options:["15 minutes","30 minutes","1 heure","Le train est annulé"],correct_answer:"30 minutes",points:1,order_index:1},
  {id:"c3d4e5f6-1111-4000-8000-100000000001",test_id:"a680f24e-7138-45b3-8698-a4007dd050d0",question_text:"Bonjour, ici la Société de transport. Nous vous informons que la ligne de bus numéro 55 sera déviée ce week-end entre 8h et 18h en raison de travaux rue Sainte-Catherine. Les arrêts entre les rues Peel et Guy ne seront pas desservis. Veuillez consulter notre site web pour connaître les arrêts temporaires. Merci de votre compréhension.\n\nQuestion : Quelle ligne de bus est concernée par la déviation ?",options:["La ligne 45","La ligne 55","La ligne 65","La ligne 75"],correct_answer:"La ligne 55",points:1,order_index:2},
  {id:"c3d4e5f6-2222-4000-8000-200000000002",test_id:"a680f24e-7138-45b3-8698-a4007dd050d0",question_text:"Bonjour, ici la Société de transport. Nous vous informons que la ligne de bus numéro 55 sera déviée ce week-end entre 8h et 18h en raison de travaux rue Sainte-Catherine. Les arrêts entre les rues Peel et Guy ne seront pas desservis. Veuillez consulter notre site web pour connaître les arrêts temporaires. Merci de votre compréhension.\n\nQuestion : Pendant combien de temps la ligne sera-t-elle déviée ?",options:["Toute la semaine","Ce week-end","Un mois","Une journée seulement"],correct_answer:"Ce week-end",points:1,order_index:3},
  {id:"c3d4e5f6-3333-4000-8000-300000000003",test_id:"a680f24e-7138-45b3-8698-a4007dd050d0",question_text:"Bienvenue à bord du vol Air Canada 845 à destination de Vancouver. L'embarquement commencera dans 15 minutes, porte 23. Nous invitons d'abord les passagers de la zone 1, soit les membres Super Elite et les personnes à mobilité réduite. Ensuite, les zones 2 et 3 seront appelées. Veuillez avoir votre carte d'embarquement et une pièce d'identité prêtes.\n\nQuestion : Quelle est la destination du vol ?",options:["Toronto","Montréal","Vancouver","Calgary"],correct_answer:"Vancouver",points:1,order_index:4},
  {id:"c3d4e5f6-4444-4000-8000-400000000004",test_id:"a680f24e-7138-45b3-8698-a4007dd050d0",question_text:"Bienvenue à bord du vol Air Canada 845 à destination de Vancouver. L'embarquement commencera dans 15 minutes, porte 23. Nous invitons d'abord les passagers de la zone 1, soit les membres Super Elite et les personnes à mobilité réduite. Ensuite, les zones 2 et 3 seront appelées. Veuillez avoir votre carte d'embarquement et une pièce d'identité prêtes.\n\nQuestion : Qui est invité à embarquer en premier ?",options:["Tous les passagers","Les passagers de la zone 2","Les membres Super Elite et personnes à mobilité réduite","Les passagers avec des enfants"],correct_answer:"Les membres Super Elite et personnes à mobilité réduite",points:1,order_index:5},
  {id:"c3d4e5f6-5555-4000-8000-500000000005",test_id:"a680f24e-7138-45b3-8698-a4007dd050d0",question_text:"Allô, c'est Marc. Je suis coincé dans le trafic sur l'autoroute 40, il y a un accident près de la sortie 65. Je vais être en retard d'au moins 20 minutes pour la réunion. Est-ce que tu peux prévenir Caroline ? Je t'envoie un message dès que je suis sorti du bouchon. Merci !\n\nQuestion : Pourquoi Marc est-il en retard ?",options:["Il a oublié la réunion","Il y a un accident sur l'autoroute","Son réveil n'a pas sonné","Il a raté le bus"],correct_answer:"Il y a un accident sur l'autoroute",points:1,order_index:6},
  {id:"c3d4e5f6-6666-4000-8000-600000000006",test_id:"a680f24e-7138-45b3-8698-a4007dd050d0",question_text:"Allô, c'est Marc. Je suis coincé dans le trafic sur l'autoroute 40, il y a un accident près de la sortie 65. Je vais être en retard d'au moins 20 minutes pour la réunion. Est-ce que tu peux prévenir Caroline ? Je t'envoie un message dès que je suis sorti du bouchon. Merci !\n\nQuestion : Que demande Marc à son interlocuteur ?",options:["De venir le chercher","De prévenir Caroline","D'annuler la réunion","De rappeler plus tard"],correct_answer:"De prévenir Caroline",points:1,order_index:7},
  {id:"c3d4e5f6-7777-4000-8000-700000000007",test_id:"a680f24e-7138-45b3-8698-a4007dd050d0",question_text:"La STM rappelle à ses usagers que pendant la période hivernale, les autobus peuvent accumuler des retards de 10 à 20 minutes en raison des conditions météorologiques difficiles. Nous vous recommandons de planifier vos déplacements en conséquence et de consulter l'application STM pour suivre les horaires en temps réel. Pour votre sécurité, restez à l'intérieur de l'abribus jusqu'à l'arrivée du véhicule.\n\nQuestion : Quel retard les autobus peuvent-ils accumuler en hiver ?",options:["5 à 10 minutes","10 à 20 minutes","30 à 40 minutes","Aucun retard"],correct_answer:"10 à 20 minutes",points:1,order_index:8},
  {id:"c3d4e5f6-8888-4000-8000-800000000008",test_id:"a680f24e-7138-45b3-8698-a4007dd050d0",question_text:"La STM rappelle à ses usagers que pendant la période hivernale, les autobus peuvent accumuler des retards de 10 à 20 minutes en raison des conditions météorologiques difficiles. Nous vous recommandons de planifier vos déplacements en conséquence et de consulter l'application STM pour suivre les horaires en temps réel. Pour votre sécurité, restez à l'intérieur de l'abribus jusqu'à l'arrivée du véhicule.\n\nQuestion : Comment peut-on suivre les horaires en temps réel ?",options:["En appelant la STM","En consultant l'application STM","En demandant au chauffeur","En regardant les panneaux publicitaires"],correct_answer:"En consultant l'application STM",points:1,order_index:9},

  // LISTENING 2: Santé (10 questions)
  {id:"2f8f8282-15a6-4a4d-bf81-63df0e0195d1",test_id:"d5dbed0d-3f59-420d-b3ad-c20763522762",question_text:"Bonjour, vous avez bien joint la clinique de santé du quartier. Nous sommes ouverts du lundi au vendredi de 8h à 20h. Pour prendre un rendez-vous avec votre médecin de famille, appuyez sur le 1. Pour les urgences mineures, veuillez vous présenter à notre clinique sans rendez-vous dès 7h30 le matin.\n\nQuestion : À quelle heure ouvre la clinique sans rendez-vous ?",options:["8h00","7h30","9h00","20h00"],correct_answer:"7h30",points:1,order_index:0},
  {id:"0c58d312-cfd2-4618-8039-3c19b4e8baa6",test_id:"d5dbed0d-3f59-420d-b3ad-c20763522762",question_text:"Bonjour, vous avez bien joint la clinique de santé du quartier. Nous sommes ouverts du lundi au vendredi de 8h à 20h. Pour prendre un rendez-vous avec votre médecin de famille, appuyez sur le 1. Pour les urgences mineures, veuillez vous présenter à notre clinique sans rendez-vous dès 7h30 le matin.\n\nQuestion : Sur quelle touche faut-il appuyer pour voir son médecin de famille ?",options:["1","2","3","4"],correct_answer:"1",points:1,order_index:1},
  {id:"d4e5f6a7-1111-4000-8000-100000000001",test_id:"d5dbed0d-3f59-420d-b3ad-c20763522762",question_text:"Bonjour madame, c'est la pharmacie Brunet. Votre prescription est prête. Vous pouvez passer la récupérer aujourd'hui avant 21h. Veuillez apporter votre carte d'assurance-maladie. Le pharmacien aimerait vous rencontrer brièvement pour vous expliquer la posologie du nouveau médicament.\n\nQuestion : Où doit-on aller récupérer la prescription ?",options:["À la clinique","À la pharmacie Brunet","À l'hôpital","Chez le médecin"],correct_answer:"À la pharmacie Brunet",points:1,order_index:2},
  {id:"d4e5f6a7-2222-4000-8000-200000000002",test_id:"d5dbed0d-3f59-420d-b3ad-c20763522762",question_text:"Bonjour madame, c'est la pharmacie Brunet. Votre prescription est prête. Vous pouvez passer la récupérer aujourd'hui avant 21h. Veuillez apporter votre carte d'assurance-maladie. Le pharmacien aimerait vous rencontrer brièvement pour vous expliquer la posologie du nouveau médicament.\n\nQuestion : Pourquoi le pharmacien veut-il rencontrer la patiente ?",options:["Pour la facturer","Pour expliquer la posologie","Pour prendre sa tension","Pour lui vendre autre chose"],correct_answer:"Pour expliquer la posologie",points:1,order_index:3},
  {id:"d4e5f6a7-3333-4000-8000-300000000003",test_id:"d5dbed0d-3f59-420d-b3ad-c20763522762",question_text:"Ici Radio-Canada, le bulletin de santé. Une nouvelle étude menée par l'Université de Montréal révèle que 30 minutes de marche quotidienne réduit de 25% le risque de maladies cardiovasculaires chez les personnes de plus de 50 ans. Les chercheurs recommandent également de combiner cette activité avec une alimentation riche en légumes et en fibres.\n\nQuestion : Combien de temps de marche est recommandé par jour ?",options:["15 minutes","30 minutes","45 minutes","1 heure"],correct_answer:"30 minutes",points:1,order_index:4},
  {id:"d4e5f6a7-4444-4000-8000-400000000004",test_id:"d5dbed0d-3f59-420d-b3ad-c20763522762",question_text:"Ici Radio-Canada, le bulletin de santé. Une nouvelle étude menée par l'Université de Montréal révèle que 30 minutes de marche quotidienne réduit de 25% le risque de maladies cardiovasculaires chez les personnes de plus de 50 ans. Les chercheurs recommandent également de combiner cette activité avec une alimentation riche en légumes et en fibres.\n\nQuestion : De quel pourcentage le risque de maladies cardiovasculaires est-il réduit ?",options:["10%","15%","25%","50%"],correct_answer:"25%",points:1,order_index:5},
  {id:"d4e5f6a7-5555-4000-8000-500000000005",test_id:"d5dbed0d-3f59-420d-b3ad-c20763522762",question_text:"Bonjour, je voudrais prendre rendez-vous avec le docteur Tremblay. — Certainement. Avez-vous une préférence de jour ? — Plutôt en fin de semaine si possible. — Voyons... jeudi prochain à 14h30, ça vous conviendrait ? — Parfait, je prends ! — Très bien, c'est noté. N'oubliez pas d'arriver 10 minutes à l'avance.\n\nQuestion : Pour quel jour le rendez-vous est-il pris ?",options:["Lundi","Mercredi","Jeudi","Vendredi"],correct_answer:"Jeudi",points:1,order_index:6},
  {id:"d4e5f6a7-6666-4000-8000-600000000006",test_id:"d5dbed0d-3f59-420d-b3ad-c20763522762",question_text:"Bonjour, je voudrais prendre rendez-vous avec le docteur Tremblay. — Certainement. Avez-vous une préférence de jour ? — Plutôt en fin de semaine si possible. — Voyons... jeudi prochain à 14h30, ça vous conviendrait ? — Parfait, je prends ! — Très bien, c'est noté. N'oubliez pas d'arriver 10 minutes à l'avance.\n\nQuestion : Combien de temps à l'avance faut-il arriver ?",options:["5 minutes","10 minutes","15 minutes","30 minutes"],correct_answer:"10 minutes",points:1,order_index:7},
  {id:"d4e5f6a7-7777-4000-8000-700000000007",test_id:"d5dbed0d-3f59-420d-b3ad-c20763522762",question_text:"Attention, alerte météo. Environnement Canada émet un avertissement de chaleur extrême pour la région de Montréal. Les températures pourraient atteindre 35 degrés avec un indice humidex de 42. Il est recommandé de boire beaucoup d'eau, de rester dans des endroits climatisés et de vérifier l'état de vos voisins âgés.\n\nQuestion : Quel est l'indice humidex prévu ?",options:["30","35","42","50"],correct_answer:"42",points:1,order_index:8},
  {id:"d4e5f6a7-8888-4000-8000-800000000008",test_id:"d5dbed0d-3f59-420d-b3ad-c20763522762",question_text:"Attention, alerte météo. Environnement Canada émet un avertissement de chaleur extrême pour la région de Montréal. Les températures pourraient atteindre 35 degrés avec un indice humidex de 42. Il est recommandé de boire beaucoup d'eau, de rester dans des endroits climatisés et de vérifier l'état de vos voisins âgés.\n\nQuestion : Que recommande-t-on de faire pour les voisins âgés ?",options:["Les ignorer","Vérifier leur état","Les évacuer obligatoirement","Les appeler seulement le weekend"],correct_answer:"Vérifier leur état",points:1,order_index:9},

  // WRITING 1 & 2 + SPEAKING 1 & 2
  {id:"4a186df1-9b31-41b0-bb2d-040e2fbac533",test_id:"589b5554-8c7a-4204-a675-80016e65f1e3",question_text:"Section A : Fait divers (80 mots minimum)\n\nVous avez lu dans un journal local qu'un chat a sauvé son maître d'un incendie. Rédigez un court article pour relater cet événement.",points:10,order_index:0},
  {id:"ef996e57-277a-447e-9d8b-d2e95c10027a",test_id:"589b5554-8c7a-4204-a675-80016e65f1e3",question_text:"Section B : Lettre d'argumentation (200 mots minimum)\n\nLe parc de votre quartier va être transformé en parking. Vous écrivez au journal de la ville pour exprimer votre mécontentement et expliquer pourquoi il est important de préserver les espaces verts.",points:20,order_index:1},
  {id:"5b094b1f-d354-4bea-9f4f-b1a733ecc01f",test_id:"bb5a47fa-ff5b-4b92-9ce1-266bbf3f2215",question_text:"Section A : Fait divers (80 mots minimum)\n\nUn groupe de jeunes a organisé un nettoyage géant de la plage locale. Rédigez un court article pour le journal de l'école.",points:10,order_index:0},
  {id:"1cc37bfb-c221-4f54-8ad9-ffbaeb6327eb",test_id:"bb5a47fa-ff5b-4b92-9ce1-266bbf3f2215",question_text:"Section B : Lettre d'argumentation (200 mots minimum)\n\nVotre entreprise veut supprimer le télétravail. Écrivez une lettre à votre directeur pour argumenter en faveur du maintien du travail à distance, en mettant en avant la productivité et le bien-être des employés.",points:20,order_index:1},
  {id:"67ad396d-0d98-4bb4-9fc3-f01303865dd3",test_id:"9f3769df-3be7-44b7-b63d-302b86fc4f98",question_text:"Section A : S'informer sur un service\n\nVous voulez vous inscrire à un club de photographie. Appelez le responsable pour obtenir des informations sur les activités, le matériel requis et les tarifs.",points:10,order_index:0},
  {id:"ad4edada-27aa-4175-91fa-83c5a9d88d88",test_id:"9f3769df-3be7-44b7-b63d-302b86fc4f98",question_text:"Section B : Convaincre un proche\n\nUn ami refuse d'aller au musée d'art moderne car il trouve cela ennuyeux. Essayez de le convaincre de vous accompagner en lui présentant une exposition particulière.",points:20,order_index:1},
  {id:"390a1a8b-f662-43b6-a3e7-36682764e478",test_id:"fe9f874d-ab9f-4678-a666-9899c9d200a9",question_text:"Section A : S'informer sur un service\n\nVous êtes intéressé par l'achat d'un vélo électrique. Appelez un magasin spécialisé pour poser des questions sur l'autonomie, la garantie et les aides financières disponibles.",points:10,order_index:0},
  {id:"39e633cf-1c9f-4f35-931c-365b003a0e49",test_id:"fe9f874d-ab9f-4678-a666-9899c9d200a9",question_text:"Section B : Convaincre un proche\n\nVotre frère utilise encore beaucoup de sacs en plastique. Essayez de le convaincre d'adopter des habitudes plus écologiques au quotidien.",points:20,order_index:1},
];

async function main() {
  console.log(`Inserting ${allQuestions.length} questions...`);
  const { error } = await supabase.from("test_questions").upsert(allQuestions, { onConflict: "id" });
  if (error) { console.error("❌ Error:", error.message); return; }
  
  // Verify
  const { count } = await supabase.from("mock_tests").select("*", { count: "exact", head: true });
  const { count: qCount } = await supabase.from("test_questions").select("*", { count: "exact", head: true });
  console.log(`\n🎉 Done! ${count} total tests, ${qCount} total questions in database.`);
}

main();
